# Croatian translation for apport
# Copyright (c) 2006 Rosetta Contributors and Canonical Ltd 2006
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-05-21 12:15+0200\n"
"PO-Revision-Date: 2012-12-27 08:38+0000\n"
"Last-Translator: freedomrun <Unknown>\n"
"Language-Team: Croatian <hr@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2013-06-28 05:10+0000\n"
"X-Generator: Launchpad (build 16681)\n"
"Language: hr\n"

#: ../apport/ui.py:124
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:124
msgid "This package does not seem to be installed correctly"
msgstr "Čini se da ovaj paket nije ispravno instaliran"

#: ../apport/ui.py:128
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:128
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""
"Ovo nije službeni %s paket. Molim vas da uklonite sve nepodržane pakete i "
"pokušate ponovno."

#: ../apport/ui.py:145
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:145
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"Instalirane su vam neke od zastarjelih verzija paketa. Molim, nadogradite "
"sljedeće pakete i provjerite ponavlja li se problem:\n"
"\n"
"%s"

#: ../apport/ui.py:251
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:251
msgid "unknown program"
msgstr "nepoznati program"

#: ../apport/ui.py:252
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:252
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "Ispričavam se, program \"%s\" se neočekivano zatvorio"

#: ../apport/ui.py:254 ../apport/ui.py:1256
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:254
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1256
#, python-format
msgid "Problem in %s"
msgstr "Problem u %s"

#: ../apport/ui.py:255
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:255
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"Vaše računalo nema dovoljno slobodne memorije za automatsku analizu problema "
"i slanje izvještaja razvojnom timu."

#. package does not exist
#: ../apport/ui.py:270 ../apport/ui.py:276 ../apport/ui.py:282
#: ../apport/ui.py:325 ../apport/ui.py:333 ../apport/ui.py:462
#: ../apport/ui.py:465 ../apport/ui.py:666 ../apport/ui.py:1069
#: ../apport/ui.py:1210 ../apport/ui.py:1214 ../apport/ui.py:1233
#: ../apport/ui.py:1239
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:270
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:276
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:282
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:325
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:333
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:462
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:465
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:666
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1069
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1210
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1214
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1233
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1239
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:268
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:285
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1052
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1072
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1083
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1094
msgid "Invalid problem report"
msgstr "Neispravan izvještaj o problemu"

#: ../apport/ui.py:271 ../apport/ui.py:1216
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:271
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1216
msgid "This problem report is damaged and cannot be processed."
msgstr "Ovaj izvještaj o problemu je oštećen i ne može biti obrađen."

#: ../apport/ui.py:277
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:277
msgid "The report belongs to a package that is not installed."
msgstr "Izvještaj pripada paketu koji nije instaliran."

#: ../apport/ui.py:283
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:283
msgid "An error occurred while attempting to process this problem report:"
msgstr "Došlo je do greške pri pokušaju obrade izvještaja o problemu:"

#: ../apport/ui.py:326
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:326
msgid "You are not allowed to access this problem report."
msgstr "Niste ovlašteni za pristup ovom izvještaju o problemu."

#: ../apport/ui.py:329
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:329
msgid "Error"
msgstr "Greška"

#: ../apport/ui.py:330
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:330
msgid "There is not enough disk space available to process this report."
msgstr "Nema dovoljno prostora na disku za obradu ovog izvještaja."

#: ../apport/ui.py:414
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:414
msgid "No package specified"
msgstr "Nema određenih paketa"

#: ../apport/ui.py:415
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:415
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Morate odrediti paket ili PID. Pogledajte --help za više informacija."

#: ../apport/ui.py:432
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:432
msgid "Invalid PID"
msgstr "Neispravan PID"

#: ../apport/ui.py:433
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:433
msgid "The specified process ID does not belong to a program."
msgstr "Navedeni ID procesa ne pripada programu."

#: ../apport/ui.py:441
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:441
msgid "Permission denied"
msgstr "Dozvola je uskraćena"

#: ../apport/ui.py:442
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:442
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"Određeni proces vam ne pripada. Molimo pokrenite program kao vlasnik procesa "
"ili kao root."

#: ../apport/ui.py:463
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:463
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "Skripta za simptome %s nije odredila pogođen paket"

#: ../apport/ui.py:466
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:466
#, python-format
msgid "Package %s does not exist"
msgstr "Paket %s ne postoji"

#: ../apport/ui.py:490 ../apport/ui.py:678 ../apport/ui.py:683
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:490
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:678
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:683
msgid "Cannot create report"
msgstr "Ne mogu napraviti izvještaj"

#: ../apport/ui.py:505 ../apport/ui.py:551 ../apport/ui.py:568
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:505
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:551
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:568
msgid "Updating problem report"
msgstr "Ažuriranje izvještaja o problemu"

#: ../apport/ui.py:506
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:506
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"Niste autor ili pretplatnik izvještaja ovog problema, moguće da je izvještaj "
"duplikat ili je već zatvoren.\n"
"\n"
"Molim napravite novi izvještaj koristeći \"apport-bug\"."

#: ../apport/ui.py:515
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:515
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""

#: ../apport/ui.py:552 ../apport/ui.py:569
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:552
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:569
msgid "No additional information collected."
msgstr "Nisu prikupljene dodatne informacije."

#: ../apport/ui.py:620
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:620
msgid "What kind of problem do you want to report?"
msgstr "Kakav problem želite prijaviti?"

#: ../apport/ui.py:637
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:637
msgid "Unknown symptom"
msgstr "Nepoznat simptom"

#: ../apport/ui.py:638
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:638
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "Simptom \"%s\" nije poznat."

#: ../apport/ui.py:669
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:669
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"Nakon zatvaranja ove poruke, molim kliknite na prozor aplikacije za prijavu "
"problema o ovome."

#: ../apport/ui.py:679 ../apport/ui.py:684
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:679
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:684
msgid "xprop failed to determine process ID of the window"
msgstr "xprop nije uspio odrediti proces ID prozora"

#: ../apport/ui.py:698
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:698
msgid "%prog <report number>"
msgstr "%prog <broj izvještaja>"

#: ../apport/ui.py:700
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:700
msgid "Specify package name."
msgstr "Odredite ime paketa."

#: ../apport/ui.py:702 ../apport/ui.py:753
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:702
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:753
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr "Dodajte dodatnu oznaku u izvještaju. Moguće je odrediti više puta."

#: ../apport/ui.py:732
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:732
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"

#: ../apport/ui.py:735
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:735
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""

#: ../apport/ui.py:737
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:737
msgid "Click a window as a target for filing a problem report."
msgstr "Kliknite na prozor kao cilj za podnošenje izvještaja o problemu."

#: ../apport/ui.py:739
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:739
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""
"Početak načina za bug ažuriranje. Opcionalno se može dodati --package."

#: ../apport/ui.py:741
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:741
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""

#: ../apport/ui.py:743
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:743
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"Navedite ime paketa u --file-bug načinu. Ovo je opcija ukoliko je --pid "
"naveden. (Podrazumijeva se ako je ime paketa navedeno kao jedini argument.)"

#: ../apport/ui.py:745
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:745
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""

#: ../apport/ui.py:747
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:747
msgid "The provided pid is a hanging application."
msgstr ""

#: ../apport/ui.py:749
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:749
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""

#: ../apport/ui.py:751
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:751
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""

#: ../apport/ui.py:755
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:755
msgid "Print the Apport version number."
msgstr "Ispis broja Apport inačice."

#: ../apport/ui.py:889
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:889
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""
"To će pokrenuti apport-retrace u prozoru terminala za ispitivanje kraha."

#: ../apport/ui.py:890
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:890
msgid "Run gdb session"
msgstr "Pokreni gdb sesiju"

#: ../apport/ui.py:891
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:891
msgid "Run gdb session without downloading debug symbols"
msgstr "Pokreni gdb sesiju bez preuzimanja simbola za ispravljanje pogrešaka"

#. TRANSLATORS: %s contains the crash report file name
#: ../apport/ui.py:893
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:893
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "Ažuriranje %s sa punim simboličkim stack tragovima"

#: ../apport/ui.py:966
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:966
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""
"Došlo je do problema s programom %s koji se promijenio otkako da se srušio."

#: ../apport/ui.py:1070
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1070
msgid "Could not determine the package or source package name."
msgstr "Ne može se odrediti paket ili naziv izvornog paketa."

#: ../apport/ui.py:1088
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1088
msgid "Unable to start web browser"
msgstr "Nije moguće pokrenuti internet preglednik"

#: ../apport/ui.py:1089
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1089
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Nije moguće pokrenuti internet preglednik za otvaranje %s."

#: ../apport/ui.py:1164
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1164
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr ""

#: ../apport/ui.py:1176
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1176
msgid "Network problem"
msgstr "Problem s mrežom"

#: ../apport/ui.py:1178
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1178
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""

#: ../apport/ui.py:1205
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1205
msgid "Memory exhaustion"
msgstr "Nedostatak memorije"

#: ../apport/ui.py:1206
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1206
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"Vaš sustav nema dovoljno memorije za obradu ovog izvještaja o rušenju "
"sustava."

#: ../apport/ui.py:1229 ../apport/ui.py:1238
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1229
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1238
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr ""

#: ../apport/ui.py:1259
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1259
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"Ne može se prijaviti ovaj problem:\n"
"\n"
"%s"

#: ../apport/ui.py:1315 ../apport/ui.py:1322
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1315
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1322
msgid "Problem already known"
msgstr "Problem je već poznat"

#: ../apport/ui.py:1316
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1316
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Ovaj problem je već prijavljen u izvještaju grešaka koji je prikazan u "
"internet pregledniku. Molim provjerite možete li dodati neke dodatne "
"informacije koje mogu pomoći razvojnom timu."

#: ../apport/ui.py:1323
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1323
msgid "This problem was already reported to developers. Thank you!"
msgstr ""

#: ../bin/apport-cli.py:74 ../debian/tmp/usr/bin/apport-cli.py:74
msgid "Press any key to continue..."
msgstr "Pritisnite bilo koju tipku za nastavak..."

#: ../bin/apport-cli.py:81 ../debian/tmp/usr/bin/apport-cli.py:81
msgid "What would you like to do? Your options are:"
msgstr "Što želite napraviti? Vaše mogućnosti su:"

#: ../bin/apport-cli.py:85 ../debian/tmp/usr/bin/apport-cli.py:85
#, python-format
msgid "Please choose (%s):"
msgstr "Molim odaberite (%s):"

#: ../bin/apport-cli.py:145 ../debian/tmp/usr/bin/apport-cli.py:145
#, python-format
msgid "(%i bytes)"
msgstr "(%i bajtova)"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:138 ../kde/apport-kde.py:338
#: ../bin/apport-cli.py:147 ../gtk/apport-gtk.py:138
#: ../debian/tmp/usr/share/apport/apport-kde.py:338
#: ../debian/tmp/usr/bin/apport-cli.py:147
msgid "(binary data)"
msgstr "(binarni podatci)"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:173
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:404
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:282
#: ../kde/apport-kde.py:162 ../bin/apport-cli.py:175 ../gtk/apport-gtk.py:173
#: ../debian/tmp/usr/share/apport/apport-kde.py:162
#: ../debian/tmp/usr/bin/apport-cli.py:175
msgid "Send problem report to the developers?"
msgstr "Pošaljite izvještaj o problemu razvojnom timu?"

#: ../bin/apport-cli.py:176 ../debian/tmp/usr/bin/apport-cli.py:176
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"Nakon slanja izvještaja o problemu, molimo ispunite formular u\n"
"automatski otvorenom internet pregledniku."

#: ../bin/apport-cli.py:179 ../debian/tmp/usr/bin/apport-cli.py:179
#, python-format
msgid "&Send report (%s)"
msgstr "&Pošaljite izvještaj (%s)"

#: ../bin/apport-cli.py:183 ../debian/tmp/usr/bin/apport-cli.py:183
msgid "&Examine locally"
msgstr ""

#: ../bin/apport-cli.py:187 ../debian/tmp/usr/bin/apport-cli.py:187
msgid "&View report"
msgstr "&Pogledajte izvještaj"

#: ../bin/apport-cli.py:188 ../debian/tmp/usr/bin/apport-cli.py:188
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"&Zadržite dokument izvještaja za kasnije slanje ili kopiranje na neko drugo "
"mjesto"

#: ../bin/apport-cli.py:189 ../debian/tmp/usr/bin/apport-cli.py:189
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Poništi i &ignoriraj buduća rušenja ove verzije programa"

#: ../bin/apport-cli.py:191 ../bin/apport-cli.py:268 ../bin/apport-cli.py:300
#: ../bin/apport-cli.py:321 ../debian/tmp/usr/bin/apport-cli.py:191
#: ../debian/tmp/usr/bin/apport-cli.py:268
#: ../debian/tmp/usr/bin/apport-cli.py:300
#: ../debian/tmp/usr/bin/apport-cli.py:321
msgid "&Cancel"
msgstr "&Odustani"

#: ../bin/apport-cli.py:219 ../debian/tmp/usr/bin/apport-cli.py:219
msgid "Problem report file:"
msgstr "Dokument izvještaja o problemu:"

#: ../bin/apport-cli.py:225 ../bin/apport-cli.py:230
#: ../debian/tmp/usr/bin/apport-cli.py:225
#: ../debian/tmp/usr/bin/apport-cli.py:230
msgid "&Confirm"
msgstr "&Potvrdi"

#: ../bin/apport-cli.py:229 ../debian/tmp/usr/bin/apport-cli.py:229
#, python-format
msgid "Error: %s"
msgstr "Greška: %s"

#: ../kde/apport-kde.py:383 ../bin/apport-cli.py:235
#: ../debian/tmp/usr/share/apport/apport-kde.py:383
#: ../debian/tmp/usr/bin/apport-cli.py:235
msgid "Collecting problem information"
msgstr "Skupljanje informacija o problemu"

#: ../bin/apport-cli.py:236 ../debian/tmp/usr/bin/apport-cli.py:236
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Prikupljene informacije mogu biti poslane razvojnom timu kako bi se "
"aplikacija\n"
"poboljšala. To može potrajati nekoliko minuta."

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13 ../gtk/apport-gtk.ui.h:13
#: ../kde/apport-kde.py:411 ../bin/apport-cli.py:248
#: ../debian/tmp/usr/share/apport/apport-kde.py:411
#: ../debian/tmp/usr/bin/apport-cli.py:248
msgid "Uploading problem information"
msgstr "Slanje informacija o problemu"

#: ../bin/apport-cli.py:249 ../debian/tmp/usr/bin/apport-cli.py:249
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Prikupljene informacije se šalju sustavu za praćenje grešaka.\n"
"Ovo može potrajati nekoliko minuta."

#: ../bin/apport-cli.py:299 ../debian/tmp/usr/bin/apport-cli.py:299
msgid "&Done"
msgstr "&Obavljeno"

#: ../bin/apport-cli.py:305 ../debian/tmp/usr/bin/apport-cli.py:305
msgid "none"
msgstr "nijedno"

#: ../bin/apport-cli.py:306 ../debian/tmp/usr/bin/apport-cli.py:306
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Označeno: %s. Višestruki izbori:"

#: ../bin/apport-cli.py:322 ../debian/tmp/usr/bin/apport-cli.py:322
msgid "Choices:"
msgstr "Izbori:"

#: ../bin/apport-cli.py:336 ../debian/tmp/usr/bin/apport-cli.py:336
msgid "Path to file (Enter to cancel):"
msgstr "Putanja do datoteke ( Enter za prekid):"

#: ../bin/apport-cli.py:342 ../debian/tmp/usr/bin/apport-cli.py:342
msgid "File does not exist."
msgstr "Datoteka ne postoji."

#: ../bin/apport-cli.py:344 ../debian/tmp/usr/bin/apport-cli.py:344
msgid "This is a directory."
msgstr "Ovo je direktorij."

#: ../bin/apport-cli.py:350 ../debian/tmp/usr/bin/apport-cli.py:350
msgid "To continue, you must visit the following URL:"
msgstr "Da biste nastavili, morate posjetiti sljedeći URL:"

#: ../bin/apport-cli.py:352 ../debian/tmp/usr/bin/apport-cli.py:352
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"Sada možete pokrenuti pretreživač, ili kopirati URL u pretreživač na drugom "
"računalu."

#: ../bin/apport-cli.py:354 ../debian/tmp/usr/bin/apport-cli.py:354
msgid "Launch a browser now"
msgstr "Sada pokrenite preglednik"

#: ../bin/apport-cli.py:368 ../debian/tmp/usr/bin/apport-cli.py:368
msgid "No pending crash reports. Try --help for more information."
msgstr ""
"Nema neposlanih izvještaja o rušenju. Pokušajte --help za više informacija."

#: ../data/apportcheckresume.py:68
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:68
msgid ""
"This occured during a previous suspend and prevented it from resuming "
"properly."
msgstr ""

#: ../data/apportcheckresume.py:70
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:70
msgid ""
"This occured during a previous hibernate and prevented it from resuming "
"properly."
msgstr ""

#: ../data/apportcheckresume.py:75
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:75
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""

#: ../bin/apport-retrace.py:31 ../debian/tmp/usr/bin/apport-retrace.py:31
msgid "%prog [options] <apport problem report | crash ID>"
msgstr ""

#: ../bin/apport-retrace.py:33 ../debian/tmp/usr/bin/apport-retrace.py:33
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""

#: ../bin/apport-retrace.py:35 ../debian/tmp/usr/bin/apport-retrace.py:35
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""

#: ../bin/apport-retrace.py:37 ../debian/tmp/usr/bin/apport-retrace.py:37
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""

#: ../bin/apport-retrace.py:39 ../debian/tmp/usr/bin/apport-retrace.py:39
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""

#: ../bin/apport-retrace.py:41 ../debian/tmp/usr/bin/apport-retrace.py:41
msgid "Override report's CoreFile"
msgstr ""

#: ../bin/apport-retrace.py:43 ../debian/tmp/usr/bin/apport-retrace.py:43
msgid "Override report's ExecutablePath"
msgstr ""

#: ../bin/apport-retrace.py:45 ../debian/tmp/usr/bin/apport-retrace.py:45
msgid "Override report's ProcMaps"
msgstr ""

#: ../bin/apport-retrace.py:47 ../debian/tmp/usr/bin/apport-retrace.py:47
msgid "Rebuild report's Package information"
msgstr "Obnovi izvješća o informacijama paketa."

#: ../bin/apport-retrace.py:49 ../debian/tmp/usr/bin/apport-retrace.py:49
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""

#: ../bin/apport-retrace.py:51 ../debian/tmp/usr/bin/apport-retrace.py:51
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-retrace.py:53 ../debian/tmp/usr/bin/apport-retrace.py:53
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""

#: ../bin/apport-retrace.py:55 ../debian/tmp/usr/bin/apport-retrace.py:55
msgid "Cache directory for packages downloaded in the sandbox"
msgstr ""

#: ../bin/apport-retrace.py:57 ../debian/tmp/usr/bin/apport-retrace.py:57
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""

#: ../bin/apport-retrace.py:59 ../bin/apport-valgrind.py:66
#: ../debian/tmp/usr/bin/apport-retrace.py:59
#: ../debian/tmp/usr/bin/apport-valgrind.py:66
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""

#: ../bin/apport-retrace.py:61 ../debian/tmp/usr/bin/apport-retrace.py:61
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""

#: ../bin/apport-retrace.py:63 ../debian/tmp/usr/bin/apport-retrace.py:63
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""

#: ../bin/apport-retrace.py:65 ../debian/tmp/usr/bin/apport-retrace.py:65
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""

#: ../bin/apport-retrace.py:70 ../debian/tmp/usr/bin/apport-retrace.py:70
msgid "incorrect number of arguments; use --help for a short help"
msgstr ""
"Netočan broj argumenata; upotrijebite --pomoć(ili --help) za kratku pomoć."

#: ../bin/apport-retrace.py:76 ../debian/tmp/usr/bin/apport-retrace.py:76
msgid "You cannot use -C without -S. Stopping."
msgstr ""

#: ../bin/apport-retrace.py:80 ../debian/tmp/usr/bin/apport-retrace.py:80
msgid ""
"you either need to do a local operation (-s, -g, -o) or supply an "
"authentication file (--auth); see --help for a short help"
msgstr ""

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../bin/apport-retrace.py:114 ../debian/tmp/usr/bin/apport-retrace.py:114
msgid "OK to send these as attachments? [y/n]"
msgstr "Jeli u redu otposlati ove privitke? [d/n]"

#: ../gtk/apport-gtk.desktop.in.h:1 ../kde/apport-kde.desktop.in.h:1
#: ../kde/apport-kde-mime.desktop.in.h:1 ../gtk/apport-gtk-mime.desktop.in.h:1
msgid "Report a problem..."
msgstr "Prijavite problem..."

#: ../gtk/apport-gtk.desktop.in.h:2 ../kde/apport-kde.desktop.in.h:2
#: ../kde/apport-kde-mime.desktop.in.h:2 ../gtk/apport-gtk-mime.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Prijavite kvar razvojnom timu"

#: ../debian/tmp/usr/share/apport/kernel_oops.py:28 ../data/kernel_oops.py:28
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""

#: ../bin/apport-valgrind.py:37 ../debian/tmp/usr/bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr ""

#: ../bin/apport-valgrind.py:43 ../debian/tmp/usr/bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr ""

#: ../bin/apport-valgrind.py:46 ../debian/tmp/usr/bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""

#: ../bin/apport-valgrind.py:50 ../debian/tmp/usr/bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""

#: ../bin/apport-valgrind.py:54 ../debian/tmp/usr/bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""

#: ../bin/apport-valgrind.py:58 ../debian/tmp/usr/bin/apport-valgrind.py:58
msgid ""
"report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-valgrind.py:62 ../debian/tmp/usr/bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""

#: ../bin/apport-valgrind.py:97 ../debian/tmp/usr/bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:153 ../gtk/apport-gtk.py:153
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:156 ../gtk/apport-gtk.py:156
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:161
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:108
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:300
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:106
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:250
#: ../kde/apport-kde.py:176 ../kde/apport-kde.py:217 ../gtk/apport-gtk.py:161
#: ../debian/tmp/usr/share/apport/apport-kde.py:176
#: ../debian/tmp/usr/share/apport/apport-kde.py:217
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:182
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:412
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:288
#: ../kde/apport-kde.py:170 ../gtk/apport-gtk.py:182
#: ../debian/tmp/usr/share/apport/apport-kde.py:170
msgid "Send"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
#: ../debian/tmp/usr/share/apport/apport-gtk.py:200
#: ../debian/tmp/usr/share/apport/apport-gtk.py:569 ../gtk/apport-gtk.ui.h:7
#: ../kde/apport-kde.py:271 ../gtk/apport-gtk.py:200 ../gtk/apport-gtk.py:569
#: ../debian/tmp/usr/share/apport/apport-kde.py:271
msgid "Show Details"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10
#: ../debian/tmp/usr/share/apport/apport-gtk.py:212
#: ../debian/tmp/usr/share/apport/apport-gtk.py:280
#: ../debian/tmp/usr/share/apport/apport-gtk.py:299
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:115
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:144
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:157
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:192
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:310
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:350
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:454
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:111
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:137
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:149
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:182
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:258
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:328
#: ../gtk/apport-gtk.ui.h:10 ../kde/apport-kde.py:210 ../kde/apport-kde.py:223
#: ../gtk/apport-gtk.py:212 ../gtk/apport-gtk.py:280 ../gtk/apport-gtk.py:299
#: ../debian/tmp/usr/share/apport/apport-kde.py:210
#: ../debian/tmp/usr/share/apport/apport-kde.py:223
msgid "Continue"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:224
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:276
#: ../gtk/apport-gtk.py:224
msgid "Force Closed"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:225
#: ../debian/tmp/usr/share/apport/apport-gtk.py:284
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:232
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:273
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:222
#: ../kde/apport-kde.py:214 ../kde/apport-kde.py:357 ../gtk/apport-gtk.py:225
#: ../gtk/apport-gtk.py:284 ../debian/tmp/usr/share/apport/apport-kde.py:214
#: ../debian/tmp/usr/share/apport/apport-kde.py:357
msgid "Relaunch"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:234 ../gtk/apport-gtk.py:234
#, python-format
msgid "The application %s has stopped responding."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:238 ../gtk/apport-gtk.py:238
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:253 ../kde/apport-kde.py:184
#: ../gtk/apport-gtk.py:253 ../debian/tmp/usr/share/apport/apport-kde.py:184
#, python-format
msgid "Package: %s"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:260
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:137
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:132
#: ../kde/apport-kde.py:190 ../gtk/apport-gtk.py:260
#: ../debian/tmp/usr/share/apport/apport-kde.py:190
msgid "Sorry, a problem occurred while installing software."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:269
#: ../debian/tmp/usr/share/apport/apport-gtk.py:288 ../kde/apport-kde.py:197
#: ../gtk/apport-gtk.py:269 ../gtk/apport-gtk.py:288
#: ../debian/tmp/usr/share/apport/apport-kde.py:197
#, python-format
msgid "The application %s has experienced an internal error."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:272 ../kde/apport-kde.py:201
#: ../gtk/apport-gtk.py:272 ../debian/tmp/usr/share/apport/apport-kde.py:201
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9
#: ../debian/tmp/usr/share/apport/apport-gtk.py:283 ../gtk/apport-gtk.ui.h:9
#: ../kde/apport-kde.py:213 ../gtk/apport-gtk.py:283
#: ../debian/tmp/usr/share/apport/apport-kde.py:213
msgid "Leave Closed"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4
#: ../debian/tmp/usr/share/apport/apport-gtk.py:296
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:302
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:342
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:252
#: ../gtk/apport-gtk.ui.h:4 ../kde/apport-kde.py:220 ../gtk/apport-gtk.py:296
#: ../debian/tmp/usr/share/apport/apport-kde.py:220
msgid "If you notice further problems, try restarting the computer."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:300 ../kde/apport-kde.py:224
#: ../gtk/apport-gtk.py:300 ../debian/tmp/usr/share/apport/apport-kde.py:224
msgid "Ignore future problems of this type"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:573 ../kde/apport-kde.py:268
#: ../gtk/apport-gtk.py:573 ../debian/tmp/usr/share/apport/apport-kde.py:268
msgid "Hide Details"
msgstr ""

#: ../kde/apport-kde.py:294 ../debian/tmp/usr/share/apport/apport-kde.py:294
msgid "Username:"
msgstr ""

#: ../kde/apport-kde.py:295 ../debian/tmp/usr/share/apport/apport-kde.py:295
msgid "Password:"
msgstr ""

#: ../kde/apport-kde.py:382 ../debian/tmp/usr/share/apport/apport-kde.py:382
msgid "Collecting Problem Information"
msgstr "Prikupljanje Informacija o Problemu"

#: ../kde/apport-kde.py:384 ../debian/tmp/usr/share/apport/apport-kde.py:384
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""

#: ../kde/apport-kde.py:410 ../debian/tmp/usr/share/apport/apport-kde.py:410
msgid "Uploading Problem Information"
msgstr "Prenos Informacija o Problemu"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15 ../gtk/apport-gtk.ui.h:15
#: ../kde/apport-kde.py:412 ../debian/tmp/usr/share/apport/apport-kde.py:412
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Prikupljene informacije se šalju sustavu za praćenje grešaka. Ovo može "
"potrajati nekoliko minuta."

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1 ../gtk/apport-gtk.ui.h:1
#: ../kde/apport-kde.py:446 ../kde/apport-kde.py:482
#: ../debian/tmp/usr/share/apport/apport-kde.py:446
#: ../debian/tmp/usr/share/apport/apport-kde.py:482
msgid "Apport"
msgstr "Apport"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid ""
"Please enter your password to access problem reports of system programs"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2 ../gtk/apport-gtk.ui.h:2
msgid "Crash report"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3 ../gtk/apport-gtk.ui.h:3
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5 ../gtk/apport-gtk.ui.h:5
msgid "Send an error report to help fix this problem"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6 ../gtk/apport-gtk.ui.h:6
msgid "Ignore future problems of this program version"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8 ../gtk/apport-gtk.ui.h:8
msgid "_Examine locally"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11 ../gtk/apport-gtk.ui.h:11
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Sakupljanje podataka o problemu</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12 ../gtk/apport-gtk.ui.h:12
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"Skupljaju se informacije koje mogu pomoći razvojnom timu pri rješavanju "
"problema koje prijavljujete."

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14 ../gtk/apport-gtk.ui.h:14
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Učitavanje informacija o problemu</b></big>"

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Apport datoteka o rušenju"

#: ../debian/tmp/usr/bin/apport-unpack.py:22 ../bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr ""

#: ../debian/tmp/usr/bin/apport-unpack.py:46 ../bin/apport-unpack.py:46
msgid "Destination directory exists and is not empty."
msgstr "Odredišni direktorji postiji i nije prazan."

#~ msgid "You can help the developers to fix the problem by reporting it."
#~ msgstr "Možete pomoći razvojnom timu da riješi problem prijavom istog."

#, python-format
#~ msgid "The package \"%s\" failed to install or upgrade."
#~ msgstr "Paket \"%s\" se nije uspio instalirati ili nadograditi"

#, no-c-format, python-format
#~ msgid "Complete report (recommended; %s)"
#~ msgstr "Potpun izvještaj (preporučeno; %s)"

#~ msgid ""
#~ "<big><b>Send problem report to the developers?</b></big>\n"
#~ "\n"
#~ "After the problem report has been sent, please fill out the form in the "
#~ "automatically opened web browser."
#~ msgstr ""
#~ "<big><b>Poslati izvještaj o problemu razvojnom timu?</b></big>\n"
#~ "\n"
#~ "Nakon što je izvještaj o problemu poslan, molim ispunite formular u "
#~ "automatski otvorenom internet pregledniku."

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other "
#~ "private information), you can help to improve the application by reporting "
#~ "the problem."
#~ msgstr ""
#~ "Ako niste radili nešto povjerljivo (unosili lozinke ili nešto slično), "
#~ "možete pomoći u poboljšanju aplikacije prijavljivanjem problema razvojnom "
#~ "timu."

#~ msgid "Application problem"
#~ msgstr "Problem s aplikacijom"

#~ msgid "_Send Report"
#~ msgstr "_Pošalji izvješće"

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other\n"
#~ "private information), you can help to improve the application by reporting\n"
#~ "the problem."
#~ msgstr ""
#~ "Ako niste radili ništa povjerljivo (unosili lozinke ili druge\n"
#~ "privatne informacije), možete pomoći unaprijediti aplikaciju prijavom\n"
#~ "problema."

#, python-format
#~ msgid "%s closed unexpectedly on %s at %s."
#~ msgstr "%s neočekivano prekinut na %s u %s."

#~ msgid "Restart _Program"
#~ msgstr "Ponovo pokreni _Program"

#, no-c-format
#~ msgid ""
#~ "<span weight=\"bold\" size=\"larger\">Sorry, the package \"%s\" failed to "
#~ "install or upgrade.</span>"
#~ msgstr ""
#~ "<span weight=\"bold\" size=\"larger\">Nažalost, paket \"%s\" se nije uspio "
#~ "instalirati ili nadograditi</span>"

#, python-format
#~ msgid "&Send complete report (recommended; %s)"
#~ msgstr "&Pošaljite potpun izvještaj (preporučeno; %s)"

#, no-c-format, python-format
#~ msgid "Reduced report (slow Internet connection; %s)"
#~ msgstr "Sažeti izvještaj (spora Internet veza; %s)"

#~ msgid "_Ignore future crashes of this program version"
#~ msgstr "_Zanemari buduća rušenja ove verzije programa"

#, python-format
#~ msgid "Send &reduced report (slow Internet connection; %s)"
#~ msgstr "Pošaljite &sažeti izvještaj (spora Internet veza; %s)"

#~ msgid ""
#~ "This will remove some large items from the report. These are very useful for "
#~ "developers to debug the problem, but might be too big for you to upload if "
#~ "you have a slow internet connection."
#~ msgstr ""
#~ "Ovo će odstraniti neke veće dijelove izvještaja. Oni su vrlo korisni "
#~ "razvojnom timu za otklanjanje problema, ali mogu biti preveliki za slanje "
#~ "ako imate sporu vezu s internetom."

#~ msgid "&Report Problem..."
#~ msgstr "&Prijavi Problem..."

#~ msgid "_Report Problem..."
#~ msgstr "_Prijavi problem..."

#~ msgid "Kernel problem"
#~ msgstr "Problem s kernelom"

#~ msgid ""
#~ "You can help the developers to fix the package by reporting the problem."
#~ msgstr ""
#~ "I vi možete pomoći razvojnom timu da popravi paket prijavom problema."

#, python-format
#~ msgid "This is not a genuine %s package"
#~ msgstr "Ovo nije izvorni %s paket"

#~ msgid "Content of the report"
#~ msgstr "Sadržaj izvještaja"

#~ msgid "Package problem"
#~ msgstr "Problem s paketom"
