# Croatian translation for apport
# Copyright (c) 2006 Rosetta Contributors and Canonical Ltd 2006
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-09-10 11:16+0200\n"
"PO-Revision-Date: 2015-04-27 21:45+0000\n"
"Last-Translator: gogo <trebelnik2@gmail.com>\n"
"Language-Team: Croatian <hr@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2017-04-05 05:22+0000\n"
"X-Generator: Launchpad (build 18335)\n"
"Language: hr\n"

#: ../gtk/apport-gtk.ui.h:1 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1
#: ../kde/apport-kde.py:469 ../kde/apport-kde.py:504 ../kde/apport-kde.py:524
#: ../debian/tmp/usr/share/apport/apport-kde.py:469
#: ../debian/tmp/usr/share/apport/apport-kde.py:504
#: ../debian/tmp/usr/share/apport/apport-kde.py:524
msgid "Apport"
msgstr "Apport"

#: ../gtk/apport-gtk.ui.h:2 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2
msgid "Cancel"
msgstr "Odustani"

#: ../gtk/apport-gtk.ui.h:3 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3
msgid "OK"
msgstr "U redu"

#: ../gtk/apport-gtk.ui.h:4 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4
msgid "Crash report"
msgstr "Izvještaj rušenja"

#: ../gtk/apport-gtk.ui.h:5 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>Nažalost, dogodila se unutrašnja greška.</b></big>"

#: ../gtk/apport-gtk.py:303 ../debian/tmp/usr/share/apport/apport-gtk.py:303
#: ../gtk/apport-gtk.ui.h:6 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
#: ../kde/apport-kde.py:241 ../debian/tmp/usr/share/apport/apport-kde.py:241
msgid "If you notice further problems, try restarting the computer."
msgstr ""
"Ako primjetite daljne probleme, pokušajte ponovno pokrenuti računalo."

#: ../gtk/apport-gtk.ui.h:7 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
msgid "Send an error report to help fix this problem"
msgstr "Pošaljite izvješće greške kako bi pomogli popraviti ovaj problem"

#: ../gtk/apport-gtk.ui.h:8 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8
msgid "Ignore future problems of this program version"
msgstr "Zanemari buduće probleme za progam ove inačice"

#: ../gtk/apport-gtk.py:207 ../gtk/apport-gtk.py:576
#: ../debian/tmp/usr/share/apport/apport-gtk.py:207
#: ../debian/tmp/usr/share/apport/apport-gtk.py:576 ../gtk/apport-gtk.ui.h:9
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9 ../kde/apport-kde.py:292
#: ../debian/tmp/usr/share/apport/apport-kde.py:292
msgid "Show Details"
msgstr "Prikaži pojedinosti"

#: ../gtk/apport-gtk.ui.h:10 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10
msgid "_Examine locally"
msgstr "_Pregledaj lokalno"

#: ../gtk/apport-gtk.py:290 ../debian/tmp/usr/share/apport/apport-gtk.py:290
#: ../gtk/apport-gtk.ui.h:11 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
#: ../kde/apport-kde.py:234 ../debian/tmp/usr/share/apport/apport-kde.py:234
msgid "Leave Closed"
msgstr "Ostavi zatvoreno"

#: ../gtk/apport-gtk.py:219 ../gtk/apport-gtk.py:287 ../gtk/apport-gtk.py:306
#: ../debian/tmp/usr/share/apport/apport-gtk.py:219
#: ../debian/tmp/usr/share/apport/apport-gtk.py:287
#: ../debian/tmp/usr/share/apport/apport-gtk.py:306 ../gtk/apport-gtk.ui.h:12
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12 ../kde/apport-kde.py:231
#: ../kde/apport-kde.py:244 ../debian/tmp/usr/share/apport/apport-kde.py:231
#: ../debian/tmp/usr/share/apport/apport-kde.py:244
msgid "Continue"
msgstr "Nastavi"

#: ../gtk/apport-gtk.ui.h:13 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Sakupljanje podataka o problemu</b></big>"

#: ../gtk/apport-gtk.ui.h:14 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"Skupljaju se informacije koje mogu pomoći razvojnom timu pri rješavanju "
"problema koje prijavljujete."

#: ../debian/tmp/usr/bin/apport-cli.py:251 ../gtk/apport-gtk.ui.h:15
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15 ../kde/apport-kde.py:435
#: ../debian/tmp/usr/share/apport/apport-kde.py:435 ../bin/apport-cli.py:251
msgid "Uploading problem information"
msgstr "Slanje informacija o problemu"

#: ../gtk/apport-gtk.ui.h:16 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:16
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Učitavanje informacija o problemu</b></big>"

#: ../gtk/apport-gtk.ui.h:17 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:17
#: ../kde/apport-kde.py:436 ../debian/tmp/usr/share/apport/apport-kde.py:436
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Prikupljene informacije se šalju sustavu za praćenje grešaka. Ovo može "
"potrajati nekoliko minuta."

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Apport datoteka o rušenju"

#: ../debian/tmp/usr/bin/apport-cli.py:150 ../gtk/apport-gtk.py:145
#: ../debian/tmp/usr/share/apport/apport-gtk.py:145 ../kde/apport-kde.py:363
#: ../debian/tmp/usr/share/apport/apport-kde.py:363 ../bin/apport-cli.py:150
msgid "(binary data)"
msgstr "(binarni podatci)"

#: ../gtk/apport-gtk.py:160 ../debian/tmp/usr/share/apport/apport-gtk.py:160
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "Aplikacija %s je neočekivano zaustavljena."

#: ../gtk/apport-gtk.py:163 ../debian/tmp/usr/share/apport/apport-gtk.py:163
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "%s se neočekivano zatvorio."

#: ../gtk/apport-gtk.py:168 ../debian/tmp/usr/share/apport/apport-gtk.py:168
#: ../kde/apport-kde.py:200 ../kde/apport-kde.py:238
#: ../debian/tmp/usr/share/apport/apport-kde.py:200
#: ../debian/tmp/usr/share/apport/apport-kde.py:238
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "%s je iskusio unutrašnju grešku."

#: ../debian/tmp/usr/bin/apport-cli.py:178 ../gtk/apport-gtk.py:180
#: ../debian/tmp/usr/share/apport/apport-gtk.py:180 ../kde/apport-kde.py:186
#: ../debian/tmp/usr/share/apport/apport-kde.py:186 ../bin/apport-cli.py:178
msgid "Send problem report to the developers?"
msgstr "Pošaljite izvještaj o problemu razvojnom timu?"

#: ../gtk/apport-gtk.py:189 ../debian/tmp/usr/share/apport/apport-gtk.py:189
#: ../kde/apport-kde.py:194 ../debian/tmp/usr/share/apport/apport-kde.py:194
msgid "Send"
msgstr "Pošalji"

#: ../gtk/apport-gtk.py:231 ../debian/tmp/usr/share/apport/apport-gtk.py:231
msgid "Force Closed"
msgstr "Prisilno zatvoreno"

#: ../gtk/apport-gtk.py:232 ../gtk/apport-gtk.py:291
#: ../debian/tmp/usr/share/apport/apport-gtk.py:232
#: ../debian/tmp/usr/share/apport/apport-gtk.py:291 ../kde/apport-kde.py:235
#: ../kde/apport-kde.py:381 ../debian/tmp/usr/share/apport/apport-kde.py:235
#: ../debian/tmp/usr/share/apport/apport-kde.py:381
msgid "Relaunch"
msgstr "Pokreni ponovo"

#: ../gtk/apport-gtk.py:241 ../debian/tmp/usr/share/apport/apport-gtk.py:241
#, python-format
msgid "The application %s has stopped responding."
msgstr "Aplikacija %s više ne odgovara."

#: ../gtk/apport-gtk.py:245 ../debian/tmp/usr/share/apport/apport-gtk.py:245
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "Program \"%s\" više ne odgovara."

#: ../gtk/apport-gtk.py:260 ../debian/tmp/usr/share/apport/apport-gtk.py:260
#: ../kde/apport-kde.py:208 ../debian/tmp/usr/share/apport/apport-kde.py:208
#, python-format
msgid "Package: %s"
msgstr "Paket: %s"

#: ../gtk/apport-gtk.py:267 ../debian/tmp/usr/share/apport/apport-gtk.py:267
#: ../kde/apport-kde.py:214 ../debian/tmp/usr/share/apport/apport-kde.py:214
msgid "Sorry, a problem occurred while installing software."
msgstr "Problem se dogodio tijekom instalacije softvera."

#: ../gtk/apport-gtk.py:276 ../gtk/apport-gtk.py:295
#: ../debian/tmp/usr/share/apport/apport-gtk.py:276
#: ../debian/tmp/usr/share/apport/apport-gtk.py:295 ../kde/apport-kde.py:220
#: ../debian/tmp/usr/share/apport/apport-kde.py:220
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "Aplikacija %s je iskusila unutrašnju grešku."

#: ../gtk/apport-gtk.py:279 ../debian/tmp/usr/share/apport/apport-gtk.py:279
#: ../kde/apport-kde.py:223 ../debian/tmp/usr/share/apport/apport-kde.py:223
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "Aplikacija %s se zatvorila neočekivano."

#: ../gtk/apport-gtk.py:307 ../debian/tmp/usr/share/apport/apport-gtk.py:307
#: ../kde/apport-kde.py:245 ../debian/tmp/usr/share/apport/apport-kde.py:245
msgid "Ignore future problems of this type"
msgstr "Zanemari buduće probleme ove vrste"

#: ../gtk/apport-gtk.py:580 ../debian/tmp/usr/share/apport/apport-gtk.py:580
#: ../kde/apport-kde.py:289 ../debian/tmp/usr/share/apport/apport-kde.py:289
msgid "Hide Details"
msgstr "Sakrij pojedinosti"

#: ../bin/apport-unpack.py:22 ../debian/tmp/usr/bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "Upotreba: %s <report> <target directory>"

#: ../bin/apport-unpack.py:47 ../debian/tmp/usr/bin/apport-unpack.py:47
msgid "Destination directory exists and is not empty."
msgstr "Odredišni direktorji postiji i nije prazan."

#: ../kde/apport-kde.py:315 ../debian/tmp/usr/share/apport/apport-kde.py:315
msgid "Username:"
msgstr "Korisničko Ime:"

#: ../kde/apport-kde.py:316 ../debian/tmp/usr/share/apport/apport-kde.py:316
msgid "Password:"
msgstr "Lozinka:"

#: ../kde/apport-kde.py:406 ../debian/tmp/usr/share/apport/apport-kde.py:406
msgid "Collecting Problem Information"
msgstr "Prikupljanje Informacija o Problemu"

#: ../debian/tmp/usr/bin/apport-cli.py:238 ../kde/apport-kde.py:407
#: ../debian/tmp/usr/share/apport/apport-kde.py:407 ../bin/apport-cli.py:238
msgid "Collecting problem information"
msgstr "Skupljanje informacija o problemu"

#: ../kde/apport-kde.py:408 ../debian/tmp/usr/share/apport/apport-kde.py:408
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"Prikupljene informacije mogu biti poslane razvijateljima kako bi se "
"aplikacija poboljšala. Ovo može potrajati nekoliko minuta."

#: ../kde/apport-kde.py:434 ../debian/tmp/usr/share/apport/apport-kde.py:434
msgid "Uploading Problem Information"
msgstr "Prenos Informacija o Problemu"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Prikupljanje informacija o sustavu"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"Ovjera je potrebna za prikupljanje informacija o sustavu za ovaj izvještaj "
"problema"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "Izvještaji o problemu sustava"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid ""
"Please enter your password to access problem reports of system programs"
msgstr ""
"Upišite svoju lozinku za pristup izvještajima problema programa sustava"

#: ../gtk/apport-gtk.desktop.in.h:1 ../kde/apport-kde.desktop.in.h:1
#: ../kde/apport-kde-mime.desktop.in.h:1
msgid "Report a problem..."
msgstr "Prijavite problem..."

#: ../gtk/apport-gtk.desktop.in.h:2 ../kde/apport-kde.desktop.in.h:2
#: ../kde/apport-kde-mime.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Prijavite neispravnost razvojnom timu"

#: ../debian/tmp/usr/bin/apport-valgrind.py:37 ../bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "Pogledajte man stranice za više pojedinosti."

#: ../debian/tmp/usr/bin/apport-valgrind.py:43 ../bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr "odredi naziv datoteke zaspisa koju je stvorio valgrind"

#: ../debian/tmp/usr/bin/apport-valgrind.py:46 ../bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""
"ponovno koristi prije stvoreni sandbox direktorij (SDIR) ili, ako ne "
"postoji, stvori ga"

#: ../debian/tmp/usr/bin/apport-valgrind.py:50 ../bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""
"ne stvaraj ili ponovno koristi sandbox direktorij za dodatne simbole "
"otklanjanja greške nego se samo oslanjaj na instalirane simbole otklanjanja "
"greške."

#: ../debian/tmp/usr/bin/apport-valgrind.py:54 ../bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""
"ponovno koristi prije stvoreni direktorij predmemorije (CDIR) ili, ako ne "
"postoji, stvori ga"

#: ../debian/tmp/usr/bin/apport-valgrind.py:58 ../bin/apport-valgrind.py:58
msgid ""
"report download/install progress when installing packages into sandbox"
msgstr ""
"prijavi napredak preuzimanja/instalacije prilikom instalacije paketa u "
"sandbox"

#: ../debian/tmp/usr/bin/apport-valgrind.py:62 ../bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""
"izvršna datoteka koja se pokreće pod valgrindovim alatom provjere memorije "
"zbog otkrivanja problema s memorijom"

#: ../debian/tmp/usr/bin/apport-retrace.py:63
#: ../debian/tmp/usr/bin/apport-valgrind.py:66 ../bin/apport-valgrind.py:66
#: ../bin/apport-retrace.py:63
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr "Instaliraj dodatne pakete u sandbox (može se odrediti više puta)"

#: ../debian/tmp/usr/bin/apport-valgrind.py:97 ../bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "Greška: %s nije izvršna datoteka. Zaustavljanje."

#: ../debian/tmp/usr/share/apport/kernel_oops.py:29 ../data/kernel_oops.py:29
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:34 ../bin/apport-retrace.py:34
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr "Ne spremaj nove podatke u izvještaj, već ih zapiši u stdout."

#: ../debian/tmp/usr/bin/apport-retrace.py:36 ../bin/apport-retrace.py:36
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""
"Pokreni interaktivnu gdb sesiju s izvještajima sadržaja jezgre (-o "
"zanemareno; ne prepisuje izvještaj)"

#: ../debian/tmp/usr/bin/apport-retrace.py:38 ../bin/apport-retrace.py:38
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""
"Zapiši izmijenjen izvještaj za zadanu datoteku umjesto promjene izvornog "
"izvještaja"

#: ../debian/tmp/usr/bin/apport-retrace.py:41 ../bin/apport-retrace.py:41
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""
"Ukloni sadržaj jezgre iz izvještaja nakon regeneracije opširnog zapisa"

#: ../debian/tmp/usr/bin/apport-retrace.py:43 ../bin/apport-retrace.py:43
msgid "Override report's CoreFile"
msgstr "Zaobiđi datoteku jezgre izvještaja"

#: ../debian/tmp/usr/bin/apport-retrace.py:45 ../bin/apport-retrace.py:45
msgid "Override report's ExecutablePath"
msgstr "Zaobiđi izvršnu putanju izvještaja"

#: ../debian/tmp/usr/bin/apport-retrace.py:47 ../bin/apport-retrace.py:47
msgid "Override report's ProcMaps"
msgstr "Zaobiđi ProcMaps izvještaja"

#: ../debian/tmp/usr/bin/apport-retrace.py:49 ../bin/apport-retrace.py:49
msgid "Rebuild report's Package information"
msgstr "Obnovi izvješća o informacijama paketa."

#: ../debian/tmp/usr/bin/apport-retrace.py:51 ../bin/apport-retrace.py:51
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""
"Izgradi privremeni sandbox i preuzmi/instaliraj potrebne pakete i simbole "
"otklanjanja greške, bez ove mogućnosti pretpostavljeno je da već imate "
"instalirane potrebne pakete i simbole otklanjanja greške na sustavu. "
"Argument ukazuje na sustav podešavanja paketa osnovnog direktorija, ako "
"odredite \"sustav\", koristit će se datoteke podešavanja sustava, ali će "
"onda samo biti moguće zapisivati rušenja koja su se dogodila na trenutno "
"pokrenutom izdanju."

#: ../debian/tmp/usr/bin/apport-retrace.py:53 ../bin/apport-retrace.py:53
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""
"Prijavi napredak preuzimanja/instalacije tijekom instalacije paketa u sandbox"

#: ../debian/tmp/usr/bin/apport-retrace.py:55 ../bin/apport-retrace.py:55
msgid "Prepend timestamps to log messages, for batch operation"
msgstr "Dodaj vremenske oznake u poruke zapisa, za skupne radnje"

#: ../debian/tmp/usr/bin/apport-retrace.py:57 ../bin/apport-retrace.py:57
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr ""
"Stvori i koristi repozitorije treće strane iz izvora navedenih u izvješću"

#: ../debian/tmp/usr/bin/apport-retrace.py:59 ../bin/apport-retrace.py:59
msgid "Cache directory for packages downloaded in the sandbox"
msgstr "Direktorij predmemorije za pakete preuzete u sandboxu"

#: ../debian/tmp/usr/bin/apport-retrace.py:61 ../bin/apport-retrace.py:61
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""
"Direktorij za neraspakirane pakete. Buduća pokretanja će pretpostaviti da "
"svaki preuzeti paket je isto tako raspakiran u sandboxu."

#: ../debian/tmp/usr/bin/apport-retrace.py:65 ../bin/apport-retrace.py:65
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"Putanja do datoteke s informacijom ovjere baze podataka rušenja. To se "
"koristi pri određivanju ID-a rušenja za slanje ponovljenog opširnog "
"zapisivanja (samo ako su -g, -o, ili -s određeni)"

#: ../debian/tmp/usr/bin/apport-retrace.py:67 ../bin/apport-retrace.py:67
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""
"Prikaži ponovljeno opširno zapisivanje i traži potvrdu prije slanja u bazu "
"podataka rušenja."

#: ../debian/tmp/usr/bin/apport-retrace.py:69 ../bin/apport-retrace.py:69
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""
"Putanja do kopije sqlite baze podataka (zadano: bez provjere ima li još "
"kopija)"

#: ../debian/tmp/usr/bin/apport-retrace.py:78 ../bin/apport-retrace.py:78
msgid "You cannot use -C without -S. Stopping."
msgstr "Ne možete koristiti -C bez -S. Zaustavljanje."

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../debian/tmp/usr/bin/apport-retrace.py:111 ../bin/apport-retrace.py:111
msgid "OK to send these as attachments? [y/n]"
msgstr "Jeli u redu otposlati ove privitke? [d/n]"

#: ../apport/ui.py:131
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:131
msgid "This package does not seem to be installed correctly"
msgstr "Izgleda da ovaj paket nije ispravno instaliran"

#: ../apport/ui.py:136
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:136
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""
"Ovo nije službeni %s paket. Uklonite sve pakete treće strane i pokušajte "
"ponovno."

#: ../apport/ui.py:153
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:153
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"Imate instalirane neke zastarjele inačice paketa. Nadogradite sljedeće "
"pakete i provjerite ponavlja li se problem:\n"
"\n"
"%s"

#: ../apport/ui.py:281
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:281
msgid "unknown program"
msgstr "nepoznati program"

#: ../apport/ui.py:282
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:282
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "Isprika, program \"%s\" se neočekivano zatvorio"

#: ../apport/ui.py:284 ../apport/ui.py:1323
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:284
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1323
#, python-format
msgid "Problem in %s"
msgstr "Problem u %s"

#: ../apport/ui.py:285
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:285
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"Vaše računalo nema dovoljno slobodne memorije za automatsku analizu problema "
"i slanje izvještaja razvijateljima."

#: ../apport/ui.py:333 ../apport/ui.py:341 ../apport/ui.py:468
#: ../apport/ui.py:471 ../apport/ui.py:672 ../apport/ui.py:1129
#: ../apport/ui.py:1295 ../apport/ui.py:1299
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:333
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:341
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:468
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:471
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:672
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1129
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1295
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1299
msgid "Invalid problem report"
msgstr "Neispravan izvještaj o problemu"

#: ../apport/ui.py:334
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:334
msgid "You are not allowed to access this problem report."
msgstr "Niste ovlašteni za pristup ovom izvještaju o problemu."

#: ../apport/ui.py:337
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:337
msgid "Error"
msgstr "Greška"

#: ../apport/ui.py:338
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:338
msgid "There is not enough disk space available to process this report."
msgstr "Nema dovoljno prostora na disku za obradu ovog izvještaja."

#: ../apport/ui.py:422
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:422
msgid "No package specified"
msgstr "Nema određenih paketa"

#: ../apport/ui.py:423
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:423
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Morate odrediti paket ili PID. Pogledajte --help za više informacija."

#: ../apport/ui.py:446
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:446
msgid "Permission denied"
msgstr "Pristup odbijen"

#: ../apport/ui.py:447
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:447
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"Određeni proces vam ne pripada. Pokrenite ovaj program kao root korisnik."

#: ../apport/ui.py:449
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:449
msgid "Invalid PID"
msgstr "Neispravan PID"

#: ../apport/ui.py:450
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:450
msgid "The specified process ID does not belong to a program."
msgstr "Određeni ID proces ne pripada programu."

#: ../apport/ui.py:469
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:469
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "Skripta simptoma %s nije odredila zahvaćeni paket"

#: ../apport/ui.py:472
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:472
#, python-format
msgid "Package %s does not exist"
msgstr "Paket %s ne postoji"

#: ../apport/ui.py:496 ../apport/ui.py:684 ../apport/ui.py:689
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:496
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:684
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:689
msgid "Cannot create report"
msgstr "Ne mogu napraviti izvještaj"

#: ../apport/ui.py:511 ../apport/ui.py:557 ../apport/ui.py:574
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:511
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:557
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:574
msgid "Updating problem report"
msgstr "Nadopuna izvještaja problema"

#: ../apport/ui.py:512
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:512
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"Niste autor ili pretplatnik ovog izvještaja problema, moguće da je izvještaj "
"kopija ili je već zatvoren.\n"
"\n"
"Napravite novi izvještaj koristeći \"apport-bug\"."

#: ../apport/ui.py:521
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:521
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"Niste autor ovog izvještaja problema. Mnogo je jednostavnije označiti "
"problem kao kopiju drugog izvještaja nego premještati vaše komentare i "
"privitke na novi izvještaj.\n"
"\n"
"Nadalje, predlažemo vam prijavu novog izvještaja problema koristeći \"apport-"
"bug\" i dodajte  komentar o ovom problemu.\n"
"\n"
"Želite li stvarno nastaviti?"

#: ../apport/ui.py:558 ../apport/ui.py:575
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:558
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:575
msgid "No additional information collected."
msgstr "Nisu prikupljene dodatne informacije."

#: ../apport/ui.py:626
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:626
msgid "What kind of problem do you want to report?"
msgstr "Kakav problem želite prijaviti?"

#: ../apport/ui.py:643
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:643
msgid "Unknown symptom"
msgstr "Nepoznat simptom"

#: ../apport/ui.py:644
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:644
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "Simptom \"%s\" nije poznat."

#: ../apport/ui.py:675
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:675
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"Nakon zatvaranja ove poruke kliknite na prozor aplikacije za prijavu ovog "
"problema."

#: ../apport/ui.py:685 ../apport/ui.py:690
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:685
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:690
msgid "xprop failed to determine process ID of the window"
msgstr "xprop nije uspio odrediti proces ID prozora"

#: ../apport/ui.py:704
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:704
msgid "%prog <report number>"
msgstr "%prog <broj izvještaja>"

#: ../apport/ui.py:706
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:706
msgid "Specify package name."
msgstr "Odredite naziv paketa."

#: ../apport/ui.py:708 ../apport/ui.py:759
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:708
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:759
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr "Dodajte dodatnu oznaku u izvještaj. Moguće je odrediti više puta."

#: ../apport/ui.py:738
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:738
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""
"%prog [mogućnosti] [simptom|pid|paket|program putanja|.apport/.crash "
"datoteka]"

#: ../apport/ui.py:741
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:741
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"Početak načina prijave greške. Zahtijeva --package i po izboru --pid, ili "
"ukratko samo --pid. Ako ni jedno nije navedeno, prikaži popis poznatih "
"simptoma. (Podrazumijeva se ako je jedan argument zadan.)"

#: ../apport/ui.py:743
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:743
msgid "Click a window as a target for filing a problem report."
msgstr "Kliknite na prozor kao cilj za podnošenje izvještaja o problemu."

#: ../apport/ui.py:745
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:745
msgid "Start in bug updating mode. Can take an optional --package."
msgstr "Početak načina nadopune greške. Može se dodati po izboru --package."

#: ../apport/ui.py:747
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:747
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""
"Prijavi izvještaj greške o simptomu. (Podrazumijeva ako je naziv simptoma "
"naveden kao jedini argument.)"

#: ../apport/ui.py:749
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:749
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"Navedite naziv paketa u --file-bug načinu. Ovo nije obavezno ako je --pid "
"naveden. (Podrazumijeva se ako je naziv paketa naveden kao jedini argument.)"

#: ../apport/ui.py:751
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:751
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""
"Navedite pokrenuti program u --file-bug načinu. Ako je naveden, izvještaj "
"greške će sadržavati više informacija. (Podrazumijeva se ako je pid naveden "
"kao jedini argument.)"

#: ../apport/ui.py:753
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:753
msgid "The provided pid is a hanging application."
msgstr "Zadani pid prekida aplikaciju."

#: ../apport/ui.py:755
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:755
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"Prijavite rušenje za zadanu .apport ili .crash datoteku umjesto onih "
"nezavršenih u %s. (Podrazumijeva se ako je datoteka zadana kao jedini "
"argument.)"

#: ../apport/ui.py:757
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:757
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""
"U načinu prijave greške, spremite prikupljene informacije u datoteku umjesto "
"da je prijavite. Ta datoteka se zatim kasnije može prijaviti s drugog "
"računala."

#: ../apport/ui.py:761
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:761
msgid "Print the Apport version number."
msgstr "Ispiši broj Apport inačice."

#: ../apport/ui.py:900
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:900
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""
"To će pokrenuti apport-retrace u prozoru terminala zbog ispitivanja rušenja."

#: ../apport/ui.py:901
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:901
msgid "Run gdb session"
msgstr "Pokreni gdb sesiju"

#: ../apport/ui.py:902
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:902
msgid "Run gdb session without downloading debug symbols"
msgstr "Pokreni gdb sesiju bez preuzimanja simbola otklanjanja greške"

#. TRANSLATORS: %s contains the crash report file name
#: ../apport/ui.py:904
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:904
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "Nadopuni %s s potpunim simboličkim opširnim zapisom"

#: ../apport/ui.py:980 ../apport/ui.py:990
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:980
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:990
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr ""
"Ovaj izvještaj problema se odnosi na program koji više nije instaliran."

#: ../apport/ui.py:1005
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1005
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""
"Dogodio se problem s programom %s koji se promijenio otkada se srušio."

#: ../apport/ui.py:1052 ../apport/ui.py:1086 ../apport/ui.py:1301
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1052
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1086
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1301
msgid "This problem report is damaged and cannot be processed."
msgstr "Ovaj izvještaj o problemu je oštećen i ne može biti obrađen."

#. package does not exist
#: ../apport/ui.py:1056
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1056
msgid "The report belongs to a package that is not installed."
msgstr "Izvještaj pripada paketu koji nije instaliran."

#: ../apport/ui.py:1060
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1060
msgid "An error occurred while attempting to process this problem report:"
msgstr "Došlo je do greške pri pokušaju obrade izvještaja problema:"

#: ../apport/ui.py:1130
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1130
msgid "Could not determine the package or source package name."
msgstr "Ne može se odrediti paket ili naziv izvornog paketa."

#: ../apport/ui.py:1148
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1148
msgid "Unable to start web browser"
msgstr "Nemoguće pokretanje Internet preglednika"

#: ../apport/ui.py:1149
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1149
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Nemoguće pokretanje Internet preglednik za otvaranje %s."

#: ../apport/ui.py:1249
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1249
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr ""
"Upišite informacije vašeg korisničkog računa za %s sustav praćenja grešaka"

#: ../apport/ui.py:1261
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1261
msgid "Network problem"
msgstr "Problem s mrežom"

#: ../apport/ui.py:1263
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1263
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""
"Nemoguće povezivanje na bazu podataka rušenja. Provjerite vaš pristup "
"Internetu."

#: ../apport/ui.py:1290
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1290
msgid "Memory exhaustion"
msgstr "Nedostatak memorije"

#: ../apport/ui.py:1291
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1291
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"Vaš sustav nema dovoljno memorije za obradu ovog izvještaja o rušenju "
"sustava."

#: ../apport/ui.py:1326
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1326
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"Ovaj problem se ne može se prijaviti:\n"
"\n"
"%s"

#: ../apport/ui.py:1382 ../apport/ui.py:1389
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1382
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1389
msgid "Problem already known"
msgstr "Problem je već poznat"

#: ../apport/ui.py:1383
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1383
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Ovaj problem je već prijavljen u izvještaju grešaka koji je prikazan u "
"internet pregledniku. Provjerite možete li dodati neke dodatne informacije "
"koje mogu pomoći razvijateljima."

#: ../apport/ui.py:1390
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1390
msgid "This problem was already reported to developers. Thank you!"
msgstr "Ovaj problem je već prijavljen razvijateljima. Hvala Vam!"

#: ../data/apportcheckresume.py:67
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr ""
"Ovo je nastalo tijekom prijašnje suspenzije i spriječilo je ispravno "
"pokretanje sustava."

#: ../data/apportcheckresume.py:69
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:69
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr ""
"Ovo je nastalo tijekom prijašnje hibernacije i spriječilo je ispravno "
"pokretanje sustava."

#: ../data/apportcheckresume.py:74
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:74
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"Postupak pokretanja se prekinuo pred sam kraj i završit će se u potpunosti "
"normalno."

#: ../debian/tmp/usr/bin/apport-cli.py:74 ../bin/apport-cli.py:74
msgid "Press any key to continue..."
msgstr "Pritisnite bilo koju tipku za nastavak..."

#: ../debian/tmp/usr/bin/apport-cli.py:81 ../bin/apport-cli.py:81
msgid "What would you like to do? Your options are:"
msgstr "Što želite napraviti? Vaše mogućnosti su:"

#: ../debian/tmp/usr/bin/apport-cli.py:85 ../bin/apport-cli.py:85
#, python-format
msgid "Please choose (%s):"
msgstr "Molim odaberite (%s):"

#: ../debian/tmp/usr/bin/apport-cli.py:148 ../bin/apport-cli.py:148
#, python-format
msgid "(%i bytes)"
msgstr "(%i bajtova)"

#: ../debian/tmp/usr/bin/apport-cli.py:179 ../bin/apport-cli.py:179
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"Nakon slanja izvještaja o problemu, molimo ispunite formular u\n"
"automatski otvorenom internet pregledniku."

#: ../debian/tmp/usr/bin/apport-cli.py:182 ../bin/apport-cli.py:182
#, python-format
msgid "&Send report (%s)"
msgstr "&Pošaljite izvještaj (%s)"

#: ../debian/tmp/usr/bin/apport-cli.py:186 ../bin/apport-cli.py:186
msgid "&Examine locally"
msgstr "&Pregledaj lokalno"

#: ../debian/tmp/usr/bin/apport-cli.py:190 ../bin/apport-cli.py:190
msgid "&View report"
msgstr "&Pogledajte izvještaj"

#: ../debian/tmp/usr/bin/apport-cli.py:191 ../bin/apport-cli.py:191
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"&Zadržite dokument izvještaja za kasnije slanje ili kopiranje na neko drugo "
"mjesto"

#: ../debian/tmp/usr/bin/apport-cli.py:192 ../bin/apport-cli.py:192
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Poništi i &ignoriraj buduća rušenja ove verzije programa"

#: ../debian/tmp/usr/bin/apport-cli.py:194
#: ../debian/tmp/usr/bin/apport-cli.py:271
#: ../debian/tmp/usr/bin/apport-cli.py:303
#: ../debian/tmp/usr/bin/apport-cli.py:324 ../bin/apport-cli.py:194
#: ../bin/apport-cli.py:271 ../bin/apport-cli.py:303 ../bin/apport-cli.py:324
msgid "&Cancel"
msgstr "&Odustani"

#: ../debian/tmp/usr/bin/apport-cli.py:222 ../bin/apport-cli.py:222
msgid "Problem report file:"
msgstr "Dokument izvještaja o problemu:"

#: ../debian/tmp/usr/bin/apport-cli.py:228
#: ../debian/tmp/usr/bin/apport-cli.py:233 ../bin/apport-cli.py:228
#: ../bin/apport-cli.py:233
msgid "&Confirm"
msgstr "&Potvrdi"

#: ../debian/tmp/usr/bin/apport-cli.py:232 ../bin/apport-cli.py:232
#, python-format
msgid "Error: %s"
msgstr "Greška: %s"

#: ../debian/tmp/usr/bin/apport-cli.py:239 ../bin/apport-cli.py:239
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Prikupljene informacije mogu biti poslane razvojnom timu kako bi se "
"aplikacija\n"
"poboljšala. To može potrajati nekoliko minuta."

#: ../debian/tmp/usr/bin/apport-cli.py:252 ../bin/apport-cli.py:252
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Prikupljene informacije se šalju sustavu za praćenje grešaka.\n"
"Ovo može potrajati nekoliko minuta."

#: ../debian/tmp/usr/bin/apport-cli.py:302 ../bin/apport-cli.py:302
msgid "&Done"
msgstr "&Obavljeno"

#: ../debian/tmp/usr/bin/apport-cli.py:308 ../bin/apport-cli.py:308
msgid "none"
msgstr "nijedno"

#: ../debian/tmp/usr/bin/apport-cli.py:309 ../bin/apport-cli.py:309
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Označeno: %s. Višestruki izbori:"

#: ../debian/tmp/usr/bin/apport-cli.py:325 ../bin/apport-cli.py:325
msgid "Choices:"
msgstr "Izbori:"

#: ../debian/tmp/usr/bin/apport-cli.py:339 ../bin/apport-cli.py:339
msgid "Path to file (Enter to cancel):"
msgstr "Putanja do datoteke ( Enter za prekid):"

#: ../debian/tmp/usr/bin/apport-cli.py:345 ../bin/apport-cli.py:345
msgid "File does not exist."
msgstr "Datoteka ne postoji."

#: ../debian/tmp/usr/bin/apport-cli.py:347 ../bin/apport-cli.py:347
msgid "This is a directory."
msgstr "Ovo je direktorij."

#: ../debian/tmp/usr/bin/apport-cli.py:353 ../bin/apport-cli.py:353
msgid "To continue, you must visit the following URL:"
msgstr "Da biste nastavili, morate posjetiti sljedeći URL:"

#: ../debian/tmp/usr/bin/apport-cli.py:355 ../bin/apport-cli.py:355
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"Sada možete pokrenuti pretreživač, ili kopirati URL u pretreživač na drugom "
"računalu."

#: ../debian/tmp/usr/bin/apport-cli.py:357 ../bin/apport-cli.py:357
msgid "Launch a browser now"
msgstr "Sada pokrenite preglednik"

#: ../debian/tmp/usr/bin/apport-cli.py:372 ../bin/apport-cli.py:372
msgid "No pending crash reports. Try --help for more information."
msgstr ""
"Nema neposlanih izvještaja o rušenju. Pokušajte --help za više informacija."

#~ msgid "You can help the developers to fix the problem by reporting it."
#~ msgstr "Možete pomoći razvojnom timu da riješi problem prijavom istog."

#, python-format
#~ msgid "The package \"%s\" failed to install or upgrade."
#~ msgstr "Paket \"%s\" se nije uspio instalirati ili nadograditi"

#, no-c-format, python-format
#~ msgid "Complete report (recommended; %s)"
#~ msgstr "Potpun izvještaj (preporučeno; %s)"

#~ msgid ""
#~ "<big><b>Send problem report to the developers?</b></big>\n"
#~ "\n"
#~ "After the problem report has been sent, please fill out the form in the "
#~ "automatically opened web browser."
#~ msgstr ""
#~ "<big><b>Poslati izvještaj o problemu razvojnom timu?</b></big>\n"
#~ "\n"
#~ "Nakon što je izvještaj o problemu poslan, molim ispunite formular u "
#~ "automatski otvorenom internet pregledniku."

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other "
#~ "private information), you can help to improve the application by reporting "
#~ "the problem."
#~ msgstr ""
#~ "Ako niste radili nešto povjerljivo (unosili lozinke ili nešto slično), "
#~ "možete pomoći u poboljšanju aplikacije prijavljivanjem problema razvojnom "
#~ "timu."

#~ msgid "Application problem"
#~ msgstr "Problem s aplikacijom"

#~ msgid "_Send Report"
#~ msgstr "_Pošalji izvješće"

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other\n"
#~ "private information), you can help to improve the application by reporting\n"
#~ "the problem."
#~ msgstr ""
#~ "Ako niste radili ništa povjerljivo (unosili lozinke ili druge\n"
#~ "privatne informacije), možete pomoći unaprijediti aplikaciju prijavom\n"
#~ "problema."

#, python-format
#~ msgid "%s closed unexpectedly on %s at %s."
#~ msgstr "%s neočekivano prekinut na %s u %s."

#~ msgid "Restart _Program"
#~ msgstr "Ponovo pokreni _Program"

#, no-c-format
#~ msgid ""
#~ "<span weight=\"bold\" size=\"larger\">Sorry, the package \"%s\" failed to "
#~ "install or upgrade.</span>"
#~ msgstr ""
#~ "<span weight=\"bold\" size=\"larger\">Nažalost, paket \"%s\" se nije uspio "
#~ "instalirati ili nadograditi</span>"

#, python-format
#~ msgid "&Send complete report (recommended; %s)"
#~ msgstr "&Pošaljite potpun izvještaj (preporučeno; %s)"

#, no-c-format, python-format
#~ msgid "Reduced report (slow Internet connection; %s)"
#~ msgstr "Sažeti izvještaj (spora Internet veza; %s)"

#~ msgid "_Ignore future crashes of this program version"
#~ msgstr "_Zanemari buduća rušenja ove verzije programa"

#, python-format
#~ msgid "Send &reduced report (slow Internet connection; %s)"
#~ msgstr "Pošaljite &sažeti izvještaj (spora Internet veza; %s)"

#~ msgid ""
#~ "This will remove some large items from the report. These are very useful for "
#~ "developers to debug the problem, but might be too big for you to upload if "
#~ "you have a slow internet connection."
#~ msgstr ""
#~ "Ovo će odstraniti neke veće dijelove izvještaja. Oni su vrlo korisni "
#~ "razvojnom timu za otklanjanje problema, ali mogu biti preveliki za slanje "
#~ "ako imate sporu vezu s internetom."

#~ msgid "&Report Problem..."
#~ msgstr "&Prijavi Problem..."

#~ msgid "_Report Problem..."
#~ msgstr "_Prijavi problem..."

#~ msgid "Kernel problem"
#~ msgstr "Problem s kernelom"

#~ msgid ""
#~ "You can help the developers to fix the package by reporting the problem."
#~ msgstr ""
#~ "I vi možete pomoći razvojnom timu da popravi paket prijavom problema."

#, python-format
#~ msgid "This is not a genuine %s package"
#~ msgstr "Ovo nije izvorni %s paket"

#~ msgid "Content of the report"
#~ msgstr "Sadržaj izvještaja"

#~ msgid "Package problem"
#~ msgstr "Problem s paketom"

#~ msgid "incorrect number of arguments; use --help for a short help"
#~ msgstr ""
#~ "Netočan broj argumenata; upotrijebite --pomoć(ili --help) za kratku pomoć."

#~ msgid ""
#~ "This occured during a previous suspend and prevented it from resuming "
#~ "properly."
#~ msgstr ""
#~ "Ovo se dogodilo tijekom prijašnje suspenzije i uzrokovalo je nepravilno "
#~ "pokretanje."

#~ msgid ""
#~ "This occured during a previous hibernate and prevented it from resuming "
#~ "properly."
#~ msgstr ""
#~ "Ovo se dogodilo tijekom prijašnje hibernacije i uzrokovalo je nepravilno "
#~ "pokretanje."

#~ msgid "Your system might become unstablenow and might need to be restarted."
#~ msgstr ""
#~ "Vaš sustav sada može postati nestabilan i možda treba biti ponovno pokrenut."

#, python-format
#~ msgid "Sorry, the application %s has closed unexpectedly."
#~ msgstr "Nažalost, aplikacija %s se neočekivano zatvorila."
