# Croatian translation for apport
# Copyright (c) 2006 Rosetta Contributors and Canonical Ltd 2006
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-05-17 09:15-0700\n"
"PO-Revision-Date: 2015-04-27 21:45+0000\n"
"Last-Translator: gogo <trebelnik2@gmail.com>\n"
"Language-Team: Croatian <hr@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2020-10-02 05:45+0000\n"
"X-Generator: Launchpad (build d50d1e75c500726862802414f880ee3e3bb759bf)\n"
"Language: hr\n"

#: ../kde/apport-kde-mime.desktop.in.h:1 ../kde/apport-kde.desktop.in.h:1
#: ../gtk/apport-gtk.desktop.in.h:1
msgid "Report a problem..."
msgstr "Prijavite problem..."

#: ../kde/apport-kde-mime.desktop.in.h:2 ../kde/apport-kde.desktop.in.h:2
#: ../gtk/apport-gtk.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Prijavite neispravnost razvojnom timu"

#: ../debian/tmp/usr/share/apport/apport-kde.py:363
#: ../debian/tmp/usr/bin/apport-cli.py:166
#: ../debian/tmp/usr/share/apport/apport-gtk.py:146 ../gtk/apport-gtk.py:146
#: ../bin/apport-cli.py:166 ../kde/apport-kde.py:363
msgid "(binary data)"
msgstr "(binarni podatci)"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:161 ../gtk/apport-gtk.py:161
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "Aplikacija %s je neočekivano zaustavljena."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:164 ../gtk/apport-gtk.py:164
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "%s se neočekivano zatvorio."

#: ../debian/tmp/usr/share/apport/apport-kde.py:200
#: ../debian/tmp/usr/share/apport/apport-kde.py:238
#: ../debian/tmp/usr/share/apport/apport-gtk.py:169 ../gtk/apport-gtk.py:169
#: ../kde/apport-kde.py:200 ../kde/apport-kde.py:238
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "%s je iskusio unutrašnju grešku."

#: ../debian/tmp/usr/share/apport/apport-kde.py:186
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
#: ../debian/tmp/usr/bin/apport-cli.py:194
#: ../debian/tmp/usr/share/apport/apport-gtk.py:181 ../gtk/apport-gtk.ui.h:6
#: ../gtk/apport-gtk.py:181 ../bin/apport-cli.py:194 ../kde/apport-kde.py:186
msgid "Send problem report to the developers?"
msgstr "Pošaljite izvještaj o problemu razvojnom timu?"

#: ../debian/tmp/usr/share/apport/apport-kde.py:194
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14
#: ../debian/tmp/usr/share/apport/apport-gtk.py:188 ../gtk/apport-gtk.ui.h:14
#: ../gtk/apport-gtk.py:188 ../kde/apport-kde.py:194
msgid "Send"
msgstr "Pošalji"

#: ../debian/tmp/usr/share/apport/apport-kde.py:292
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
#: ../debian/tmp/usr/share/apport/apport-gtk.py:204
#: ../debian/tmp/usr/share/apport/apport-gtk.py:575 ../gtk/apport-gtk.ui.h:11
#: ../gtk/apport-gtk.py:204 ../gtk/apport-gtk.py:575 ../kde/apport-kde.py:292
msgid "Show Details"
msgstr "Prikaži pojedinosti"

#: ../debian/tmp/usr/share/apport/apport-kde.py:231
#: ../debian/tmp/usr/share/apport/apport-kde.py:244
#: ../debian/tmp/usr/share/apport/apport-gtk.py:216 ../gtk/apport-gtk.py:216
#: ../kde/apport-kde.py:231 ../kde/apport-kde.py:244
msgid "Continue"
msgstr "Nastavi"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:239 ../gtk/apport-gtk.py:239
#, python-format
msgid "The application %s has stopped responding."
msgstr "Aplikacija %s više ne odgovara."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:243 ../gtk/apport-gtk.py:243
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "Program \"%s\" više ne odgovara."

#: ../debian/tmp/usr/share/apport/apport-kde.py:208
#: ../debian/tmp/usr/share/apport/apport-gtk.py:259 ../gtk/apport-gtk.py:259
#: ../kde/apport-kde.py:208
#, python-format
msgid "Package: %s"
msgstr "Paket: %s"

#: ../debian/tmp/usr/share/apport/apport-kde.py:214
#: ../debian/tmp/usr/share/apport/apport-gtk.py:265 ../gtk/apport-gtk.py:265
#: ../kde/apport-kde.py:214
msgid "Sorry, a problem occurred while installing software."
msgstr "Problem se dogodio tijekom instalacije softvera."

#: ../debian/tmp/usr/share/apport/apport-kde.py:220
#: ../debian/tmp/usr/share/apport/apport-gtk.py:274
#: ../debian/tmp/usr/share/apport/apport-gtk.py:289 ../gtk/apport-gtk.py:274
#: ../gtk/apport-gtk.py:289 ../kde/apport-kde.py:220
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "Aplikacija %s je iskusila unutrašnju grešku."

#: ../debian/tmp/usr/share/apport/apport-kde.py:223
#: ../debian/tmp/usr/share/apport/apport-gtk.py:277 ../gtk/apport-gtk.py:277
#: ../kde/apport-kde.py:223
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "Aplikacija %s se zatvorila neočekivano."

#: ../debian/tmp/usr/share/apport/apport-kde.py:241
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
#: ../debian/tmp/usr/share/apport/apport-gtk.py:297 ../gtk/apport-gtk.ui.h:7
#: ../gtk/apport-gtk.py:297 ../kde/apport-kde.py:241
msgid "If you notice further problems, try restarting the computer."
msgstr ""
"Ako primjetite daljne probleme, pokušajte ponovno pokrenuti računalo."

#: ../debian/tmp/usr/share/apport/apport-kde.py:245
#: ../debian/tmp/usr/share/apport/apport-gtk.py:299 ../gtk/apport-gtk.py:299
#: ../kde/apport-kde.py:245
msgid "Ignore future problems of this type"
msgstr "Zanemari buduće probleme ove vrste"

#: ../debian/tmp/usr/share/apport/apport-kde.py:289
#: ../debian/tmp/usr/share/apport/apport-gtk.py:579 ../gtk/apport-gtk.py:579
#: ../kde/apport-kde.py:289
msgid "Hide Details"
msgstr "Sakrij pojedinosti"

#: ../bin/apport-retrace.py:34 ../debian/tmp/usr/bin/apport-retrace.py:34
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr "Ne spremaj nove podatke u izvještaj, već ih zapiši u stdout."

#: ../bin/apport-retrace.py:36 ../debian/tmp/usr/bin/apport-retrace.py:36
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""
"Pokreni interaktivnu gdb sesiju s izvještajima sadržaja jezgre (-o "
"zanemareno; ne prepisuje izvještaj)"

#: ../bin/apport-retrace.py:38 ../debian/tmp/usr/bin/apport-retrace.py:38
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""
"Zapiši izmijenjen izvještaj za zadanu datoteku umjesto promjene izvornog "
"izvještaja"

#: ../bin/apport-retrace.py:41 ../debian/tmp/usr/bin/apport-retrace.py:41
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""
"Ukloni sadržaj jezgre iz izvještaja nakon regeneracije opširnog zapisa"

#: ../bin/apport-retrace.py:43 ../debian/tmp/usr/bin/apport-retrace.py:43
msgid "Override report's CoreFile"
msgstr "Zaobiđi datoteku jezgre izvještaja"

#: ../bin/apport-retrace.py:45 ../debian/tmp/usr/bin/apport-retrace.py:45
msgid "Override report's ExecutablePath"
msgstr "Zaobiđi izvršnu putanju izvještaja"

#: ../bin/apport-retrace.py:47 ../debian/tmp/usr/bin/apport-retrace.py:47
msgid "Override report's ProcMaps"
msgstr "Zaobiđi ProcMaps izvještaja"

#: ../bin/apport-retrace.py:49 ../debian/tmp/usr/bin/apport-retrace.py:49
msgid "Rebuild report's Package information"
msgstr "Obnovi izvješća o informacijama paketa."

#: ../bin/apport-retrace.py:51 ../debian/tmp/usr/bin/apport-retrace.py:51
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""
"Izgradi privremeni sandbox i preuzmi/instaliraj potrebne pakete i simbole "
"otklanjanja greške, bez ove mogućnosti pretpostavljeno je da već imate "
"instalirane potrebne pakete i simbole otklanjanja greške na sustavu. "
"Argument ukazuje na sustav podešavanja paketa osnovnog direktorija, ako "
"odredite \"sustav\", koristit će se datoteke podešavanja sustava, ali će "
"onda samo biti moguće zapisivati rušenja koja su se dogodila na trenutno "
"pokrenutom izdanju."

#: ../bin/apport-retrace.py:53 ../debian/tmp/usr/bin/apport-retrace.py:53
msgid ""
"Build another temporary sandbox for installing gdb and its dependencies "
"using the same release as the report rather than whatever version of gdb you "
"have installed."
msgstr ""
"Izgradi dodatno osigurano okruženje za gdb instalaciju i pripadajuće "
"zavisnosti upotrebom istog izdanja kao izvještaja bez obzira koju gdb "
"inačicu imate instaliranu."

#: ../bin/apport-retrace.py:55 ../debian/tmp/usr/bin/apport-retrace.py:55
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""
"Prijavi napredak preuzimanja/instalacije tijekom instalacije paketa u sandbox"

#: ../bin/apport-retrace.py:57 ../debian/tmp/usr/bin/apport-retrace.py:57
msgid "Prepend timestamps to log messages, for batch operation"
msgstr "Dodaj vremenske oznake u poruke zapisa, za skupne radnje"

#: ../bin/apport-retrace.py:59 ../debian/tmp/usr/bin/apport-retrace.py:59
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr ""
"Stvori i koristi repozitorije treće strane iz izvora navedenih u izvješću"

#: ../bin/apport-retrace.py:61 ../debian/tmp/usr/bin/apport-retrace.py:61
msgid "Cache directory for packages downloaded in the sandbox"
msgstr "Direktorij predmemorije za pakete preuzete u sandboxu"

#: ../bin/apport-retrace.py:63 ../debian/tmp/usr/bin/apport-retrace.py:63
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""
"Direktorij za neraspakirane pakete. Buduća pokretanja će pretpostaviti da "
"svaki preuzeti paket je isto tako raspakiran u sandboxu."

#: ../bin/apport-retrace.py:65 ../bin/apport-valgrind.py:66
#: ../debian/tmp/usr/bin/apport-retrace.py:65
#: ../debian/tmp/usr/bin/apport-valgrind.py:66
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr "Instaliraj dodatne pakete u sandbox (može se odrediti više puta)"

#: ../bin/apport-retrace.py:67 ../debian/tmp/usr/bin/apport-retrace.py:67
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"Putanja do datoteke s informacijom ovjere baze podataka rušenja. To se "
"koristi pri određivanju ID-a rušenja za slanje ponovljenog opširnog "
"zapisivanja (samo ako su -g, -o, ili -s određeni)"

#: ../bin/apport-retrace.py:69 ../debian/tmp/usr/bin/apport-retrace.py:69
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""
"Prikaži ponovljeno opširno zapisivanje i traži potvrdu prije slanja u bazu "
"podataka rušenja."

#: ../bin/apport-retrace.py:71 ../debian/tmp/usr/bin/apport-retrace.py:71
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""
"Putanja do kopije sqlite baze podataka (zadano: bez provjere ima li još "
"kopija)"

#: ../bin/apport-retrace.py:73 ../debian/tmp/usr/bin/apport-retrace.py:73
msgid "Do not add StacktraceSource to the report."
msgstr "Nemoj dodati opširni zapis u izvješće."

#: ../bin/apport-retrace.py:82 ../debian/tmp/usr/bin/apport-retrace.py:82
msgid "You cannot use -C without -S. Stopping."
msgstr "Ne možete koristiti -C bez -S. Zaustavljanje."

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../bin/apport-retrace.py:115 ../debian/tmp/usr/bin/apport-retrace.py:115
msgid "OK to send these as attachments? [y/n]"
msgstr "Jeli u redu otposlati ove privitke? [d/n]"

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Apport datoteka o rušenju"

#: ../bin/apport-valgrind.py:37 ../debian/tmp/usr/bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "Pogledajte man stranice za više pojedinosti."

#: ../bin/apport-valgrind.py:43 ../debian/tmp/usr/bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr "odredi naziv datoteke zaspisa koju je stvorio valgrind"

#: ../bin/apport-valgrind.py:46 ../debian/tmp/usr/bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""
"ponovno koristi prije stvoreni sandbox direktorij (SDIR) ili, ako ne "
"postoji, stvori ga"

#: ../bin/apport-valgrind.py:50 ../debian/tmp/usr/bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""
"ne stvaraj ili ponovno koristi sandbox direktorij za dodatne simbole "
"otklanjanja greške nego se samo oslanjaj na instalirane simbole otklanjanja "
"greške."

#: ../bin/apport-valgrind.py:54 ../debian/tmp/usr/bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""
"ponovno koristi prije stvoreni direktorij predmemorije (CDIR) ili, ako ne "
"postoji, stvori ga"

#: ../bin/apport-valgrind.py:58 ../debian/tmp/usr/bin/apport-valgrind.py:58
msgid ""
"report download/install progress when installing packages into sandbox"
msgstr ""
"prijavi napredak preuzimanja/instalacije prilikom instalacije paketa u "
"sandbox"

#: ../bin/apport-valgrind.py:62 ../debian/tmp/usr/bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""
"izvršna datoteka koja se pokreće pod valgrindovim alatom provjere memorije "
"zbog otkrivanja problema s memorijom"

#: ../bin/apport-valgrind.py:97 ../debian/tmp/usr/bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "Greška: %s nije izvršna datoteka. Zaustavljanje."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:139
#: ../apport/ui.py:139
msgid "This package does not seem to be installed correctly"
msgstr "Izgleda da ovaj paket nije ispravno instaliran"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:130
#: ../apport/ui.py:130
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""
"Ovo nije službeni %s paket. Uklonite sve pakete treće strane i pokušajte "
"ponovno."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:166
#: ../apport/ui.py:166
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"Imate instalirane neke zastarjele inačice paketa. Nadogradite sljedeće "
"pakete i provjerite ponavlja li se problem:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:303
#: ../apport/ui.py:303
msgid "unknown program"
msgstr "nepoznati program"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:304
#: ../apport/ui.py:304
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "Isprika, program \"%s\" se neočekivano zatvorio"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:306
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1458
#: ../apport/ui.py:306 ../apport/ui.py:1458
#, python-format
msgid "Problem in %s"
msgstr "Problem u %s"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:307
#: ../apport/ui.py:307
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"Vaše računalo nema dovoljno slobodne memorije za automatsku analizu problema "
"i slanje izvještaja razvijateljima."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:362
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:370
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:519
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:522
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:727
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1264
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1430
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1434
#: ../apport/ui.py:362 ../apport/ui.py:370 ../apport/ui.py:519
#: ../apport/ui.py:522 ../apport/ui.py:727 ../apport/ui.py:1264
#: ../apport/ui.py:1430 ../apport/ui.py:1434
msgid "Invalid problem report"
msgstr "Neispravan izvještaj o problemu"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:363
#: ../apport/ui.py:363
msgid "You are not allowed to access this problem report."
msgstr "Niste ovlašteni za pristup ovom izvještaju o problemu."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:366
#: ../apport/ui.py:366
msgid "Error"
msgstr "Greška"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:367
#: ../apport/ui.py:367
msgid "There is not enough disk space available to process this report."
msgstr "Nema dovoljno prostora na disku za obradu ovog izvještaja."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:411
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:500
#: ../apport/ui.py:411 ../apport/ui.py:500
msgid "Invalid PID"
msgstr "Neispravan PID"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:412
#: ../apport/ui.py:412
msgid "The specified process ID does not exist."
msgstr "Određeni ID procesa ne postoji."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:415
#: ../apport/ui.py:415
msgid "Not your PID"
msgstr "Nije vaš PID"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:416
#: ../apport/ui.py:416
msgid "The specified process ID does not belong to you."
msgstr "Određeni ID procesa vam ne pripada."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:467
#: ../apport/ui.py:467
msgid "No package specified"
msgstr "Nema određenih paketa"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:468
#: ../apport/ui.py:468
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Morate odrediti paket ili PID. Pogledajte --help za više informacija."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:497
#: ../apport/ui.py:497
msgid "Permission denied"
msgstr "Pristup odbijen"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:498
#: ../apport/ui.py:498
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"Određeni proces vam ne pripada. Pokrenite ovaj program kao root korisnik."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:501
#: ../apport/ui.py:501
msgid "The specified process ID does not belong to a program."
msgstr "Određeni ID proces ne pripada programu."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:520
#: ../apport/ui.py:520
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "Skripta simptoma %s nije odredila zahvaćeni paket"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:523
#: ../apport/ui.py:523
#, python-format
msgid "Package %s does not exist"
msgstr "Paket %s ne postoji"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:552
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:739
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:744
#: ../apport/ui.py:552 ../apport/ui.py:739 ../apport/ui.py:744
msgid "Cannot create report"
msgstr "Ne mogu napraviti izvještaj"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:567
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:613
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:629
#: ../apport/ui.py:567 ../apport/ui.py:613 ../apport/ui.py:629
msgid "Updating problem report"
msgstr "Nadopuna izvještaja problema"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:568
#: ../apport/ui.py:568
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"Niste autor ili pretplatnik ovog izvještaja problema, moguće da je izvještaj "
"kopija ili je već zatvoren.\n"
"\n"
"Napravite novi izvještaj koristeći \"apport-bug\"."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:577
#: ../apport/ui.py:577
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"Niste autor ovog izvještaja problema. Mnogo je jednostavnije označiti "
"problem kao kopiju drugog izvještaja nego premještati vaše komentare i "
"privitke na novi izvještaj.\n"
"\n"
"Nadalje, predlažemo vam prijavu novog izvještaja problema koristeći \"apport-"
"bug\" i dodajte  komentar o ovom problemu.\n"
"\n"
"Želite li stvarno nastaviti?"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:614
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:630
#: ../apport/ui.py:614 ../apport/ui.py:630
msgid "No additional information collected."
msgstr "Nisu prikupljene dodatne informacije."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:681
#: ../apport/ui.py:681
msgid "What kind of problem do you want to report?"
msgstr "Kakav problem želite prijaviti?"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:698
#: ../apport/ui.py:698
msgid "Unknown symptom"
msgstr "Nepoznat simptom"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:699
#: ../apport/ui.py:699
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "Simptom \"%s\" nije poznat."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:730
#: ../apport/ui.py:730
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"Nakon zatvaranja ove poruke kliknite na prozor aplikacije za prijavu ovog "
"problema."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:740
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:745
#: ../apport/ui.py:740 ../apport/ui.py:745
msgid "xprop failed to determine process ID of the window"
msgstr "xprop nije uspio odrediti proces ID prozora"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:759
#: ../apport/ui.py:759
msgid "%prog <report number>"
msgstr "%prog <broj izvještaja>"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:761
#: ../apport/ui.py:761
msgid "Specify package name."
msgstr "Odredite naziv paketa."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:763
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:815
#: ../apport/ui.py:763 ../apport/ui.py:815
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr "Dodajte dodatnu oznaku u izvještaj. Moguće je odrediti više puta."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:794
#: ../apport/ui.py:794
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""
"%prog [mogućnosti] [simptom|pid|paket|program putanja|.apport/.crash "
"datoteka]"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:797
#: ../apport/ui.py:797
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"Početak načina prijave greške. Zahtijeva --package i po izboru --pid, ili "
"ukratko samo --pid. Ako ni jedno nije navedeno, prikaži popis poznatih "
"simptoma. (Podrazumijeva se ako je jedan argument zadan.)"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:799
#: ../apport/ui.py:799
msgid "Click a window as a target for filing a problem report."
msgstr "Kliknite na prozor kao cilj za podnošenje izvještaja o problemu."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:801
#: ../apport/ui.py:801
msgid "Start in bug updating mode. Can take an optional --package."
msgstr "Početak načina nadopune greške. Može se dodati po izboru --package."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:803
#: ../apport/ui.py:803
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""
"Prijavi izvještaj greške o simptomu. (Podrazumijeva ako je naziv simptoma "
"naveden kao jedini argument.)"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:805
#: ../apport/ui.py:805
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"Navedite naziv paketa u --file-bug načinu. Ovo nije obavezno ako je --pid "
"naveden. (Podrazumijeva se ako je naziv paketa naveden kao jedini argument.)"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:807
#: ../apport/ui.py:807
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""
"Navedite pokrenuti program u --file-bug načinu. Ako je naveden, izvještaj "
"greške će sadržavati više informacija. (Podrazumijeva se ako je pid naveden "
"kao jedini argument.)"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:809
#: ../apport/ui.py:809
msgid "The provided pid is a hanging application."
msgstr "Zadani pid prekida aplikaciju."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:811
#: ../apport/ui.py:811
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"Prijavite rušenje za zadanu .apport ili .crash datoteku umjesto onih "
"nezavršenih u %s. (Podrazumijeva se ako je datoteka zadana kao jedini "
"argument.)"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:813
#: ../apport/ui.py:813
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""
"U načinu prijave greške, spremite prikupljene informacije u datoteku umjesto "
"da je prijavite. Ta datoteka se zatim kasnije može prijaviti s drugog "
"računala."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:817
#: ../apport/ui.py:817
msgid "Print the Apport version number."
msgstr "Ispiši broj Apport inačice."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:968
#: ../apport/ui.py:968
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""
"To će pokrenuti apport-retrace u prozoru terminala zbog ispitivanja rušenja."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:969
#: ../apport/ui.py:969
msgid "Run gdb session"
msgstr "Pokreni gdb sesiju"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:970
#: ../apport/ui.py:970
msgid "Run gdb session without downloading debug symbols"
msgstr "Pokreni gdb sesiju bez preuzimanja simbola otklanjanja greške"

#. TRANSLATORS: %s contains the crash report file name
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:972
#: ../apport/ui.py:972
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "Nadopuni %s s potpunim simboličkim opširnim zapisom"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1008
#: ../apport/ui.py:1008
msgid "Can't remember send report status settings"
msgstr "Nemoguće zapamtiti postavke stanja slanja izvještaja"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1009
#: ../apport/ui.py:1009
msgid ""
"Saving crash reporting state failed. Can't set auto or never reporting mode."
msgstr ""
"Neuspješno spremanje stanja izvještaja rušenja. Nemoguće postavljanje "
"automatskog ili isključenog načina."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1068
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1078
#: ../apport/ui.py:1068 ../apport/ui.py:1078
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr ""
"Ovaj izvještaj problema se odnosi na program koji više nije instaliran."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1093
#: ../apport/ui.py:1093
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""
"Dogodio se problem s programom %s koji se promijenio otkada se srušio."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1140
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1221
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1436
#: ../apport/ui.py:1140 ../apport/ui.py:1221 ../apport/ui.py:1436
msgid "This problem report is damaged and cannot be processed."
msgstr "Ovaj izvještaj o problemu je oštećen i ne može biti obrađen."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1130
#: ../apport/ui.py:1130
#, python-format
msgid ""
"This report is about a snap published by %s. Contact them via %s for help."
msgstr ""
"Ovaj izvještaj je o snap paketu objavljenom od strane %s. Kontaktirajte ga "
"putem %s za pomoć."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1133
#: ../apport/ui.py:1133
#, python-format
msgid ""
"This report is about a snap published by %s. No contact address has been "
"provided; visit the forum at https://forum.snapcraft.io/ for help."
msgstr ""
"Ovaj izvještaj je o snap paketu objavljenom od strane %s. Nema adrese za "
"kontakt; posjetite forum na https://forum.snapcraft.io/ za pomoć."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1145
#: ../apport/ui.py:1145
msgid "This report is about a package that is not installed."
msgstr "Ovaj izvještaj je o paketu koji nije instaliran."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1149
#: ../apport/ui.py:1149
msgid "An error occurred while attempting to process this problem report:"
msgstr "Došlo je do greške pri pokušaju obrade izvještaja problema:"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1148
#: ../apport/ui.py:1148
#, python-format
msgid ""
"You are about to report a bug against the deb package, but you also a have "
"snap published by %s installed. You can contact them via %s for help. Do you "
"want to continue with the bug report against the deb?"
msgstr ""
"Imate izvještaj o deb paketu, ali imate instaliran i snap paket objavljen od "
"strane %s. Možete ih kontaktirati putem %s za pomoć. Želite li nastaviti s "
"prijavom greške deb paketa?"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1150
#: ../apport/ui.py:1150
#, python-format
msgid ""
"You are about to report a bug against the deb package, but you also a have "
"snap published by %s installed. For the snap, no contact address has been "
"provided; visit the forum at https://forum.snapcraft.io/ for help. Do you "
"want to continue with the bug report against the deb?"
msgstr ""
"Imate izvještaj o deb paketu, ali imate instaliran i snap paket objavljen od "
"strane %s. Za snap paket, nema adrese za kontakt; posjetite forum na "
"https://forum.snapcraft.io/ za pomoć. Želite li nastaviti s prijavom greške "
"deb paketa?"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1265
#: ../apport/ui.py:1265
msgid "Could not determine the package or source package name."
msgstr "Ne može se odrediti paket ili naziv izvornog paketa."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1283
#: ../apport/ui.py:1283
msgid "Unable to start web browser"
msgstr "Nemoguće pokretanje Internet preglednika"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1284
#: ../apport/ui.py:1284
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Nemoguće pokretanje Internet preglednik za otvaranje %s."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1384
#: ../apport/ui.py:1384
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr ""
"Upišite informacije vašeg korisničkog računa za %s sustav praćenja grešaka"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1396
#: ../apport/ui.py:1396
msgid "Network problem"
msgstr "Problem s mrežom"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1398
#: ../apport/ui.py:1398
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""
"Nemoguće povezivanje na bazu podataka rušenja. Provjerite vaš pristup "
"Internetu."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1425
#: ../apport/ui.py:1425
msgid "Memory exhaustion"
msgstr "Nedostatak memorije"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1426
#: ../apport/ui.py:1426
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"Vaš sustav nema dovoljno memorije za obradu ovog izvještaja o rušenju "
"sustava."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1461
#: ../apport/ui.py:1461
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"Ovaj problem se ne može se prijaviti:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1517
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1524
#: ../apport/ui.py:1517 ../apport/ui.py:1524
msgid "Problem already known"
msgstr "Problem je već poznat"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1518
#: ../apport/ui.py:1518
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Ovaj problem je već prijavljen u izvještaju grešaka koji je prikazan u "
"internet pregledniku. Provjerite možete li dodati neke dodatne informacije "
"koje mogu pomoći razvijateljima."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1525
#: ../apport/ui.py:1525
msgid "This problem was already reported to developers. Thank you!"
msgstr "Ovaj problem je već prijavljen razvijateljima. Hvala Vam!"

#: ../debian/tmp/usr/share/apport/apport-kde.py:469
#: ../debian/tmp/usr/share/apport/apport-kde.py:504
#: ../debian/tmp/usr/share/apport/apport-kde.py:524
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1 ../gtk/apport-gtk.ui.h:1
#: ../kde/apport-kde.py:469 ../kde/apport-kde.py:504 ../kde/apport-kde.py:524
msgid "Apport"
msgstr "Apport"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2 ../gtk/apport-gtk.ui.h:2
msgid "Cancel"
msgstr "Odustani"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3 ../gtk/apport-gtk.ui.h:3
msgid "OK"
msgstr "U redu"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4 ../gtk/apport-gtk.ui.h:4
msgid "Crash report"
msgstr "Izvještaj rušenja"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5 ../gtk/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>Nažalost, dogodila se unutrašnja greška.</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8 ../gtk/apport-gtk.ui.h:8
msgid "Remember this in future"
msgstr "Zapamti ovo za ubuduće"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9 ../gtk/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr "Zanemari buduće probleme za progam ove inačice"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10 ../gtk/apport-gtk.ui.h:10
msgid "Relaunch this application"
msgstr "Ponovno pokreni ovu aplikaciju"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12 ../gtk/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr "_Pregledaj lokalno"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13 ../gtk/apport-gtk.ui.h:13
msgid "Don't send"
msgstr "Ne šalji"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15 ../gtk/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Sakupljanje podataka o problemu</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:16 ../gtk/apport-gtk.ui.h:16
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"Skupljaju se informacije koje mogu pomoći razvojnom timu pri rješavanju "
"problema koje prijavljujete."

#: ../debian/tmp/usr/share/apport/apport-kde.py:435
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:17
#: ../debian/tmp/usr/bin/apport-cli.py:267 ../gtk/apport-gtk.ui.h:17
#: ../bin/apport-cli.py:267 ../kde/apport-kde.py:435
msgid "Uploading problem information"
msgstr "Slanje informacija o problemu"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:18 ../gtk/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Učitavanje informacija o problemu</b></big>"

#: ../debian/tmp/usr/share/apport/apport-kde.py:436
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:19 ../gtk/apport-gtk.ui.h:19
#: ../kde/apport-kde.py:436
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Prikupljene informacije se šalju sustavu za praćenje grešaka. Ovo može "
"potrajati nekoliko minuta."

#: ../debian/tmp/usr/share/apport/kernel_oops.py:29 ../data/kernel_oops.py:29
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""

#: ../bin/apport-unpack.py:22 ../debian/tmp/usr/bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "Upotreba: %s <report> <target directory>"

#: ../bin/apport-unpack.py:42 ../debian/tmp/usr/bin/apport-unpack.py:42
msgid "Destination directory exists and is not empty."
msgstr "Odredišni direktorji postiji i nije prazan."

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Prikupljanje informacija o sustavu"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"Ovjera je potrebna za prikupljanje informacija o sustavu za ovaj izvještaj "
"problema"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "Izvještaji o problemu sustava"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid ""
"Please enter your password to access problem reports of system programs"
msgstr ""
"Upišite svoju lozinku za pristup izvještajima problema programa sustava"

#: ../debian/tmp/usr/bin/apport-cli.py:80 ../bin/apport-cli.py:80
msgid "Press any key to continue..."
msgstr "Pritisnite bilo koju tipku za nastavak..."

#: ../debian/tmp/usr/bin/apport-cli.py:87 ../bin/apport-cli.py:87
msgid "What would you like to do? Your options are:"
msgstr "Što želite napraviti? Vaše mogućnosti su:"

#: ../debian/tmp/usr/bin/apport-cli.py:100 ../bin/apport-cli.py:100
#, python-format
msgid "Please choose (%s):"
msgstr "Molim odaberite (%s):"

#: ../debian/tmp/usr/bin/apport-cli.py:164 ../bin/apport-cli.py:164
#, python-format
msgid "(%i bytes)"
msgstr "(%i bajtova)"

#: ../debian/tmp/usr/bin/apport-cli.py:195 ../bin/apport-cli.py:195
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"Nakon slanja izvještaja o problemu, molimo ispunite formular u\n"
"automatski otvorenom internet pregledniku."

#: ../debian/tmp/usr/bin/apport-cli.py:198 ../bin/apport-cli.py:198
#, python-format
msgid "&Send report (%s)"
msgstr "&Pošaljite izvještaj (%s)"

#: ../debian/tmp/usr/bin/apport-cli.py:202 ../bin/apport-cli.py:202
msgid "&Examine locally"
msgstr "&Pregledaj lokalno"

#: ../debian/tmp/usr/bin/apport-cli.py:206 ../bin/apport-cli.py:206
msgid "&View report"
msgstr "&Pogledajte izvještaj"

#: ../debian/tmp/usr/bin/apport-cli.py:207 ../bin/apport-cli.py:207
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"&Zadržite dokument izvještaja za kasnije slanje ili kopiranje na neko drugo "
"mjesto"

#: ../debian/tmp/usr/bin/apport-cli.py:208 ../bin/apport-cli.py:208
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Poništi i &ignoriraj buduća rušenja ove verzije programa"

#: ../debian/tmp/usr/bin/apport-cli.py:210
#: ../debian/tmp/usr/bin/apport-cli.py:287
#: ../debian/tmp/usr/bin/apport-cli.py:319
#: ../debian/tmp/usr/bin/apport-cli.py:340 ../bin/apport-cli.py:210
#: ../bin/apport-cli.py:287 ../bin/apport-cli.py:319 ../bin/apport-cli.py:340
msgid "&Cancel"
msgstr "&Odustani"

#: ../debian/tmp/usr/bin/apport-cli.py:238 ../bin/apport-cli.py:238
msgid "Problem report file:"
msgstr "Dokument izvještaja o problemu:"

#: ../debian/tmp/usr/bin/apport-cli.py:244
#: ../debian/tmp/usr/bin/apport-cli.py:249 ../bin/apport-cli.py:244
#: ../bin/apport-cli.py:249
msgid "&Confirm"
msgstr "&Potvrdi"

#: ../debian/tmp/usr/bin/apport-cli.py:248 ../bin/apport-cli.py:248
#, python-format
msgid "Error: %s"
msgstr "Greška: %s"

#: ../debian/tmp/usr/share/apport/apport-kde.py:407
#: ../debian/tmp/usr/bin/apport-cli.py:254 ../bin/apport-cli.py:254
#: ../kde/apport-kde.py:407
msgid "Collecting problem information"
msgstr "Skupljanje informacija o problemu"

#: ../debian/tmp/usr/bin/apport-cli.py:255 ../bin/apport-cli.py:255
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Prikupljene informacije mogu biti poslane razvojnom timu kako bi se "
"aplikacija\n"
"poboljšala. To može potrajati nekoliko minuta."

#: ../debian/tmp/usr/bin/apport-cli.py:268 ../bin/apport-cli.py:268
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Prikupljene informacije se šalju sustavu za praćenje grešaka.\n"
"Ovo može potrajati nekoliko minuta."

#: ../debian/tmp/usr/bin/apport-cli.py:318 ../bin/apport-cli.py:318
msgid "&Done"
msgstr "&Obavljeno"

#: ../debian/tmp/usr/bin/apport-cli.py:324 ../bin/apport-cli.py:324
msgid "none"
msgstr "nijedno"

#: ../debian/tmp/usr/bin/apport-cli.py:325 ../bin/apport-cli.py:325
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Označeno: %s. Višestruki izbori:"

#: ../debian/tmp/usr/bin/apport-cli.py:341 ../bin/apport-cli.py:341
msgid "Choices:"
msgstr "Izbori:"

#: ../debian/tmp/usr/bin/apport-cli.py:355 ../bin/apport-cli.py:355
msgid "Path to file (Enter to cancel):"
msgstr "Putanja do datoteke ( Enter za prekid):"

#: ../debian/tmp/usr/bin/apport-cli.py:361 ../bin/apport-cli.py:361
msgid "File does not exist."
msgstr "Datoteka ne postoji."

#: ../debian/tmp/usr/bin/apport-cli.py:363 ../bin/apport-cli.py:363
msgid "This is a directory."
msgstr "Ovo je direktorij."

#: ../debian/tmp/usr/bin/apport-cli.py:369 ../bin/apport-cli.py:369
msgid "To continue, you must visit the following URL:"
msgstr "Da biste nastavili, morate posjetiti sljedeći URL:"

#: ../debian/tmp/usr/bin/apport-cli.py:371 ../bin/apport-cli.py:371
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"Sada možete pokrenuti pretreživač, ili kopirati URL u pretreživač na drugom "
"računalu."

#: ../debian/tmp/usr/bin/apport-cli.py:373 ../bin/apport-cli.py:373
msgid "Launch a browser now"
msgstr "Sada pokrenite preglednik"

#: ../debian/tmp/usr/bin/apport-cli.py:388 ../bin/apport-cli.py:388
msgid "No pending crash reports. Try --help for more information."
msgstr ""
"Nema neposlanih izvještaja o rušenju. Pokušajte --help za više informacija."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
#: ../data/apportcheckresume.py:67
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr ""
"Ovo je nastalo tijekom prijašnje suspenzije i spriječilo je ispravno "
"pokretanje sustava."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:69
#: ../data/apportcheckresume.py:69
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr ""
"Ovo je nastalo tijekom prijašnje hibernacije i spriječilo je ispravno "
"pokretanje sustava."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:74
#: ../data/apportcheckresume.py:74
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"Postupak pokretanja se prekinuo pred sam kraj i završit će se u potpunosti "
"normalno."

#: ../debian/tmp/usr/share/apport/apport-kde.py:234 ../kde/apport-kde.py:234
msgid "Leave Closed"
msgstr "Ostavi zatvoreno"

#: ../debian/tmp/usr/share/apport/apport-kde.py:235
#: ../debian/tmp/usr/share/apport/apport-kde.py:381 ../kde/apport-kde.py:235
#: ../kde/apport-kde.py:381
msgid "Relaunch"
msgstr "Pokreni ponovo"

#: ../debian/tmp/usr/share/apport/apport-kde.py:315 ../kde/apport-kde.py:315
msgid "Username:"
msgstr "Korisničko Ime:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:316 ../kde/apport-kde.py:316
msgid "Password:"
msgstr "Lozinka:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:406 ../kde/apport-kde.py:406
msgid "Collecting Problem Information"
msgstr "Prikupljanje Informacija o Problemu"

#: ../debian/tmp/usr/share/apport/apport-kde.py:408 ../kde/apport-kde.py:408
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"Prikupljene informacije mogu biti poslane razvijateljima kako bi se "
"aplikacija poboljšala. Ovo može potrajati nekoliko minuta."

#: ../debian/tmp/usr/share/apport/apport-kde.py:434 ../kde/apport-kde.py:434
msgid "Uploading Problem Information"
msgstr "Prenos Informacija o Problemu"

#~ msgid "You can help the developers to fix the problem by reporting it."
#~ msgstr "Možete pomoći razvojnom timu da riješi problem prijavom istog."

#, python-format
#~ msgid "The package \"%s\" failed to install or upgrade."
#~ msgstr "Paket \"%s\" se nije uspio instalirati ili nadograditi"

#, no-c-format, python-format
#~ msgid "Complete report (recommended; %s)"
#~ msgstr "Potpun izvještaj (preporučeno; %s)"

#~ msgid ""
#~ "<big><b>Send problem report to the developers?</b></big>\n"
#~ "\n"
#~ "After the problem report has been sent, please fill out the form in the "
#~ "automatically opened web browser."
#~ msgstr ""
#~ "<big><b>Poslati izvještaj o problemu razvojnom timu?</b></big>\n"
#~ "\n"
#~ "Nakon što je izvještaj o problemu poslan, molim ispunite formular u "
#~ "automatski otvorenom internet pregledniku."

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other "
#~ "private information), you can help to improve the application by reporting "
#~ "the problem."
#~ msgstr ""
#~ "Ako niste radili nešto povjerljivo (unosili lozinke ili nešto slično), "
#~ "možete pomoći u poboljšanju aplikacije prijavljivanjem problema razvojnom "
#~ "timu."

#~ msgid "Application problem"
#~ msgstr "Problem s aplikacijom"

#~ msgid "_Send Report"
#~ msgstr "_Pošalji izvješće"

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other\n"
#~ "private information), you can help to improve the application by reporting\n"
#~ "the problem."
#~ msgstr ""
#~ "Ako niste radili ništa povjerljivo (unosili lozinke ili druge\n"
#~ "privatne informacije), možete pomoći unaprijediti aplikaciju prijavom\n"
#~ "problema."

#, python-format
#~ msgid "%s closed unexpectedly on %s at %s."
#~ msgstr "%s neočekivano prekinut na %s u %s."

#~ msgid "Restart _Program"
#~ msgstr "Ponovo pokreni _Program"

#, no-c-format
#~ msgid ""
#~ "<span weight=\"bold\" size=\"larger\">Sorry, the package \"%s\" failed to "
#~ "install or upgrade.</span>"
#~ msgstr ""
#~ "<span weight=\"bold\" size=\"larger\">Nažalost, paket \"%s\" se nije uspio "
#~ "instalirati ili nadograditi</span>"

#, python-format
#~ msgid "&Send complete report (recommended; %s)"
#~ msgstr "&Pošaljite potpun izvještaj (preporučeno; %s)"

#, no-c-format, python-format
#~ msgid "Reduced report (slow Internet connection; %s)"
#~ msgstr "Sažeti izvještaj (spora Internet veza; %s)"

#~ msgid "_Ignore future crashes of this program version"
#~ msgstr "_Zanemari buduća rušenja ove verzije programa"

#, python-format
#~ msgid "Send &reduced report (slow Internet connection; %s)"
#~ msgstr "Pošaljite &sažeti izvještaj (spora Internet veza; %s)"

#~ msgid ""
#~ "This will remove some large items from the report. These are very useful for "
#~ "developers to debug the problem, but might be too big for you to upload if "
#~ "you have a slow internet connection."
#~ msgstr ""
#~ "Ovo će odstraniti neke veće dijelove izvještaja. Oni su vrlo korisni "
#~ "razvojnom timu za otklanjanje problema, ali mogu biti preveliki za slanje "
#~ "ako imate sporu vezu s internetom."

#~ msgid "&Report Problem..."
#~ msgstr "&Prijavi Problem..."

#~ msgid "The report belongs to a package that is not installed."
#~ msgstr "Izvještaj pripada paketu koji nije instaliran."

#~ msgid "_Report Problem..."
#~ msgstr "_Prijavi problem..."

#~ msgid "Kernel problem"
#~ msgstr "Problem s kernelom"

#~ msgid ""
#~ "You can help the developers to fix the package by reporting the problem."
#~ msgstr ""
#~ "I vi možete pomoći razvojnom timu da popravi paket prijavom problema."

#, python-format
#~ msgid "This is not a genuine %s package"
#~ msgstr "Ovo nije izvorni %s paket"

#~ msgid "Content of the report"
#~ msgstr "Sadržaj izvještaja"

#~ msgid "Package problem"
#~ msgstr "Problem s paketom"

#~ msgid "incorrect number of arguments; use --help for a short help"
#~ msgstr ""
#~ "Netočan broj argumenata; upotrijebite --pomoć(ili --help) za kratku pomoć."

#~ msgid "Send an error report to help fix this problem"
#~ msgstr "Pošaljite izvješće greške kako bi pomogli popraviti ovaj problem"

#~ msgid "Force Closed"
#~ msgstr "Prisilno zatvoreno"

#~ msgid ""
#~ "This occured during a previous suspend and prevented it from resuming "
#~ "properly."
#~ msgstr ""
#~ "Ovo se dogodilo tijekom prijašnje suspenzije i uzrokovalo je nepravilno "
#~ "pokretanje."

#~ msgid ""
#~ "This occured during a previous hibernate and prevented it from resuming "
#~ "properly."
#~ msgstr ""
#~ "Ovo se dogodilo tijekom prijašnje hibernacije i uzrokovalo je nepravilno "
#~ "pokretanje."

#~ msgid "Your system might become unstablenow and might need to be restarted."
#~ msgstr ""
#~ "Vaš sustav sada može postati nestabilan i možda treba biti ponovno pokrenut."

#, python-format
#~ msgid "Sorry, the application %s has closed unexpectedly."
#~ msgstr "Nažalost, aplikacija %s se neočekivano zatvorila."
