# Icelandic translation for apport
# Copyright (c) 2008 Rosetta Contributors and Canonical Ltd 2008
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2008.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-10-25 06:19+0200\n"
"PO-Revision-Date: 2013-10-23 07:55+0000\n"
"Last-Translator: Páll Haraldsson <Pall.Haraldsson@gmail.com>\n"
"Language-Team: Icelandic <is@li.org>\n"
"Language: is\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2013-10-24 04:30+0000\n"
"X-Generator: Launchpad (build 16810)\n"

#: ../apport/ui.py:124
msgid "This package does not seem to be installed correctly"
msgstr "Þessi pakki virðist ekki rétt upp settur"

#: ../apport/ui.py:128
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""

#: ../apport/ui.py:145
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"Þú er með uppsettar einhverjar úreltar útgáfur af pökkum. Endilega uppfærðu "
"eftirfarandi pakka og athugaðu hvort vandamálið endurtekur sig:\n"
"\n"
"%s"

#: ../apport/ui.py:251
msgid "unknown program"
msgstr "óþekkt forrit"

#: ../apport/ui.py:252
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "Fyrirgefðu, forritið \"%s\" hætti óvænt"

#: ../apport/ui.py:254 ../apport/ui.py:1255
#, python-format
msgid "Problem in %s"
msgstr "Vandamál í %s"

#: ../apport/ui.py:255
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"Tölvan þín hefur ekki nóg laust innra minni til að greina sjálfkrafa "
"vandamálið og senda til forritaranna."

#. package does not exist
#: ../apport/ui.py:270 ../apport/ui.py:276 ../apport/ui.py:282
#: ../apport/ui.py:320 ../apport/ui.py:328 ../apport/ui.py:455
#: ../apport/ui.py:458 ../apport/ui.py:659 ../apport/ui.py:1086
#: ../apport/ui.py:1227 ../apport/ui.py:1231
msgid "Invalid problem report"
msgstr "Ógild vandamálsskýrsla"

#: ../apport/ui.py:271 ../apport/ui.py:1233
msgid "This problem report is damaged and cannot be processed."
msgstr "Skýrslan er löskuð og ég get ekki unnið úr henni"

#: ../apport/ui.py:277
msgid "The report belongs to a package that is not installed."
msgstr "Þessi skýrsla tilheyrir pakka sem ekki er uppsettur"

#: ../apport/ui.py:283
msgid "An error occurred while attempting to process this problem report:"
msgstr "Villa kom upp þegar reynt var að vinna þessa villuskýrslu:"

#: ../apport/ui.py:321
msgid "You are not allowed to access this problem report."
msgstr "Þú hefur ekki leyfi til að skoða þessa skýrslu."

#: ../apport/ui.py:324
msgid "Error"
msgstr "Villa"

#: ../apport/ui.py:325
msgid "There is not enough disk space available to process this report."
msgstr "Það er ekki nóg diskpláss til að vinna úr skýrslunni."

#: ../apport/ui.py:409
msgid "No package specified"
msgstr "Enginn pakki valinn"

#: ../apport/ui.py:410
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Þú þarft að tilgreina pakka eða PID. Sjá --help fyrir meiri upplýsingar."

#: ../apport/ui.py:433
msgid "Permission denied"
msgstr "Aðgangur bannaður"

#: ../apport/ui.py:434
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"Tiltekið ferli tilheyrir þér ekki. Keyrðu þetta forrit sem eigandi ferlisins "
"eða sem kerfisstjórnandi"

#: ../apport/ui.py:436
msgid "Invalid PID"
msgstr "Ógilt PID"

#: ../apport/ui.py:437
msgid "The specified process ID does not belong to a program."
msgstr "Þetta ID tilheyrir ekki neinu forriti."

#: ../apport/ui.py:456
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr ""

#: ../apport/ui.py:459
#, python-format
msgid "Package %s does not exist"
msgstr "Pakki %s er ekki til"

#: ../apport/ui.py:483 ../apport/ui.py:671 ../apport/ui.py:676
msgid "Cannot create report"
msgstr ""

#: ../apport/ui.py:498 ../apport/ui.py:544 ../apport/ui.py:561
msgid "Updating problem report"
msgstr "Uppfæri villuskýrslu"

#: ../apport/ui.py:499
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"Þú ert ekki tilkynnandi eða áskrifandi að þessarri villuskýrslu, eða "
"skýrslan er tvítekin eða nú þegar lokuð.\n"
"\n"
"Búðu til nýja skýrslu með ‚apport-bug‘."

#: ../apport/ui.py:508
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-bug"
"\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"Þú ert ekki tilkynnandi þessarar villuskýrslu. Mun auðveldara er að merkja "
"villu sem tvítekningu annarrar heldur en að færa athugasemdir og viðhengin "
"þín í nýja villu.\n"
"\n"
"Þar af leiðir ráðleggjum við að þú sendir inn nýja villuskýrslu með ‚apport-"
"bug‘ og búir til athugasemd í þessarri villu um þá skýrslu.\n"
"\n"
"Ertu alveg viss þú viljir halda áfram?"

#: ../apport/ui.py:545 ../apport/ui.py:562
msgid "No additional information collected."
msgstr ""

#: ../apport/ui.py:613
msgid "What kind of problem do you want to report?"
msgstr "Hvers konar forrit viltu senda skýrslu um?"

#: ../apport/ui.py:630
msgid "Unknown symptom"
msgstr "Óþekkt einkenni"

#: ../apport/ui.py:631
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "Einkennið „%s“ er ekki þekkt."

#: ../apport/ui.py:662
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"Eftir lokun þessa skilaboða, smelltu á forritsglugga til að skrá villu um "
"hann."

#: ../apport/ui.py:672 ../apport/ui.py:677
msgid "xprop failed to determine process ID of the window"
msgstr ""

#: ../apport/ui.py:691
msgid "%prog <report number>"
msgstr ""

#: ../apport/ui.py:693
msgid "Specify package name."
msgstr "Tilgreindu pakkaheiti."

#: ../apport/ui.py:695 ../apport/ui.py:746
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""

#: ../apport/ui.py:725
msgid "%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr "%prog [options] [symptom|pid|package|program path|.apport/.crash file]"

#: ../apport/ui.py:728
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""

#: ../apport/ui.py:730
msgid "Click a window as a target for filing a problem report."
msgstr ""

#: ../apport/ui.py:732
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""

#: ../apport/ui.py:734
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""

#: ../apport/ui.py:736
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""

#: ../apport/ui.py:738
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""

#: ../apport/ui.py:740
msgid "The provided pid is a hanging application."
msgstr "Gefna PID-ið er forrit sem hangir."

#: ../apport/ui.py:742
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""

#: ../apport/ui.py:744
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""

#: ../apport/ui.py:748
msgid "Print the Apport version number."
msgstr "Gefa Apport útgáfunúmerið."

#: ../apport/ui.py:888
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""

#: ../apport/ui.py:889
msgid "Run gdb session"
msgstr ""

#: ../apport/ui.py:890
msgid "Run gdb session without downloading debug symbols"
msgstr ""

#. TRANSLATORS: %s contains the crash report file name
#: ../apport/ui.py:892
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr ""

#: ../apport/ui.py:965 ../apport/ui.py:975
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr "Þessi vandamálaskýrsla á við forrit sem er ekki uppsett lengur."

#: ../apport/ui.py:989
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""
"Vandamálið kom fyrir í forritunu %s sem er breytt síðan síðasta hrun varð."

#: ../apport/ui.py:1087
msgid "Could not determine the package or source package name."
msgstr "Gat ekki ákveðið nafn pakka eða grunnpakka"

#: ../apport/ui.py:1105
msgid "Unable to start web browser"
msgstr "Gat ekki ræst vefvafra"

#: ../apport/ui.py:1106
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Gat ekki ræst vefvafra til að opna %s"

#: ../apport/ui.py:1181
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr "Sláðu inn aðgangsupplýsingar þínar fyrir %s villukerfið."

#: ../apport/ui.py:1193
msgid "Network problem"
msgstr "Vandamál með nettengingu"

#: ../apport/ui.py:1195
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr "Get ekki tengst við gagnagrunn, athugaðu nettenginguna."

#: ../apport/ui.py:1222
msgid "Memory exhaustion"
msgstr "Minnisvandamál"

#: ../apport/ui.py:1223
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"Kerfið þitt hefur ekki nóg vinnsluminni til að vinna úr þessari skýrslu."

#: ../apport/ui.py:1258
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"Ekki hægt að tilkynna vandamálið:\n"
"\n"
"%s"

#: ../apport/ui.py:1314 ../apport/ui.py:1321
msgid "Problem already known"
msgstr "Vandamál þegar þekkt"

#: ../apport/ui.py:1315
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Þetta vandamál var þegar tilkynnt í villuskýrslunni sem birtist í "
"vefvafranum. Athugaðu hvort þú getur bætt við einhverjum gagnlegum "
"upplýsingum."

#: ../apport/ui.py:1322
msgid "This problem was already reported to developers. Thank you!"
msgstr ""
"Þetta vandamál hefur nú þegar verið tilkynnt til þróunarteymis. Takk fyrir!"

#: ../bin/apport-cli.py:74
msgid "Press any key to continue..."
msgstr "Ýttu á einhvern lykil til að halda áfram..."

#: ../bin/apport-cli.py:81
msgid "What would you like to do? Your options are:"
msgstr "Hvað viltu gera? Þú getur:"

#: ../bin/apport-cli.py:85
#, python-format
msgid "Please choose (%s):"
msgstr "Veldu (%s);"

#: ../bin/apport-cli.py:145
#, python-format
msgid "(%i bytes)"
msgstr "(%i bæti)"

#: ../bin/apport-cli.py:147 ../gtk/apport-gtk.py:138 ../kde/apport-kde.py:338
msgid "(binary data)"
msgstr "(gögn í tvíundakerfi)"

#: ../bin/apport-cli.py:175 ../gtk/apport-gtk.py:173 ../kde/apport-kde.py:162
msgid "Send problem report to the developers?"
msgstr "Senda vandamálsskýrslu til forritara?"

#: ../bin/apport-cli.py:176
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"Eftir að vandamálaskýrslan hefur verið send opnast sjálfkrafa netvafri með "
"formi.\n"
"Vinsamlegast fylltu það út."

#: ../bin/apport-cli.py:179
#, python-format
msgid "&Send report (%s)"
msgstr "&Senda skýrslu (%s)"

#: ../bin/apport-cli.py:183
msgid "&Examine locally"
msgstr "Skoða &hér"

#: ../bin/apport-cli.py:187
msgid "&View report"
msgstr "&Lesa skýrslu"

#: ../bin/apport-cli.py:188
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr "&Geyma skýrslu til að senda inn seinna eða til að færa á annan stað"

#: ../bin/apport-cli.py:189
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Hætta við og h&unsa frekari hrun í þessari útgáfu forritsins"

#: ../bin/apport-cli.py:191 ../bin/apport-cli.py:268 ../bin/apport-cli.py:300
#: ../bin/apport-cli.py:321
msgid "&Cancel"
msgstr "&Hætta við"

#: ../bin/apport-cli.py:219
msgid "Problem report file:"
msgstr "Skrá með upplýsingar um vandamál:"

#: ../bin/apport-cli.py:225 ../bin/apport-cli.py:230
msgid "&Confirm"
msgstr "&Staðfesta"

#: ../bin/apport-cli.py:229
#, python-format
msgid "Error: %s"
msgstr "Villa: %s"

#: ../bin/apport-cli.py:235 ../kde/apport-kde.py:383
msgid "Collecting problem information"
msgstr "Safna saman upplýsingum um vandamál"

#: ../bin/apport-cli.py:236
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Þú getur sent inn skýrslu með þessum upplýsingum til að bæta forritið.\n"
"Þetta getur tekið nokkra stund."

#: ../bin/apport-cli.py:248 ../kde/apport-kde.py:411 ../gtk/apport-gtk.ui.h:13
msgid "Uploading problem information"
msgstr "Sendi vandamálsskýrslu"

#: ../bin/apport-cli.py:249
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Verið er að senda upplýsingar sem safnað hefur verið í villukerfi.\n"
"Það getur tekið nokkrar mínútur."

#: ../bin/apport-cli.py:299
msgid "&Done"
msgstr "&Lokið"

#: ../bin/apport-cli.py:305
msgid "none"
msgstr "ekkert"

#: ../bin/apport-cli.py:306
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Valið: %s. Margir valkostir:"

#: ../bin/apport-cli.py:322
msgid "Choices:"
msgstr "Valkostir:"

#: ../bin/apport-cli.py:336
msgid "Path to file (Enter to cancel):"
msgstr "Slóð skráar (Enter til að hætta við):"

#: ../bin/apport-cli.py:342
msgid "File does not exist."
msgstr "Skrá er ekki til."

#: ../bin/apport-cli.py:344
msgid "This is a directory."
msgstr "Þetta er mappa."

#: ../bin/apport-cli.py:350
msgid "To continue, you must visit the following URL:"
msgstr "Þú verður að heimsækja eftirfarandi slóð til að halda áfram:"

#: ../bin/apport-cli.py:352
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"Þú getur ræst vafra núna eða afritað þessa slóð í vafra á annari tölvu."

#: ../bin/apport-cli.py:354
msgid "Launch a browser now"
msgstr "Ræsa netvafra"

#: ../bin/apport-cli.py:368
msgid "No pending crash reports. Try --help for more information."
msgstr ""

#: ../data/apportcheckresume.py:68
msgid ""
"This occured during a previous suspend and prevented it from resuming "
"properly."
msgstr ""
"Þetta gerðist áður meðan verið var í svæfingu og kom í veg fyrir "
"endurvakningu úr því ástandi."

#: ../data/apportcheckresume.py:70
msgid ""
"This occured during a previous hibernate and prevented it from resuming "
"properly."
msgstr ""
"Þetta gerðist áður meðan verið var í dvala og kom í veg fyrir endurvakningu "
"úr því ástandi."

#: ../data/apportcheckresume.py:75
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"Endurvakningin hékk í blá endann en lítur út fyrir að hafa klárast eðlilega."

#: ../bin/apport-retrace.py:31
msgid "%prog [options] <apport problem report | crash ID>"
msgstr "%prog [options] <apport problem report | crash ID>"

#: ../bin/apport-retrace.py:33
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""

#: ../bin/apport-retrace.py:35
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""

#: ../bin/apport-retrace.py:37
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""

#: ../bin/apport-retrace.py:39
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""

#: ../bin/apport-retrace.py:41
msgid "Override report's CoreFile"
msgstr ""

#: ../bin/apport-retrace.py:43
msgid "Override report's ExecutablePath"
msgstr ""

#: ../bin/apport-retrace.py:45
msgid "Override report's ProcMaps"
msgstr ""

#: ../bin/apport-retrace.py:47
msgid "Rebuild report's Package information"
msgstr ""

#: ../bin/apport-retrace.py:49
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""

#: ../bin/apport-retrace.py:51
msgid "Report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-retrace.py:53
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""

#: ../bin/apport-retrace.py:55
msgid "Cache directory for packages downloaded in the sandbox"
msgstr ""

#: ../bin/apport-retrace.py:57
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""

#: ../bin/apport-retrace.py:59 ../bin/apport-valgrind.py:66
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""

#: ../bin/apport-retrace.py:61
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""

#: ../bin/apport-retrace.py:63
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""

#: ../bin/apport-retrace.py:65
msgid "Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""

#: ../bin/apport-retrace.py:70
msgid "incorrect number of arguments; use --help for a short help"
msgstr ""

#: ../bin/apport-retrace.py:76
msgid "You cannot use -C without -S. Stopping."
msgstr "Þú getur ekki notað -C án -S. Hætti."

#: ../bin/apport-retrace.py:80
msgid ""
"you either need to do a local operation (-s, -g, -o) or supply an "
"authentication file (--auth); see --help for a short help"
msgstr ""

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../bin/apport-retrace.py:114
msgid "OK to send these as attachments? [y/n]"
msgstr "Er allt í lagi að senda þetta sem sem viðhengi? [y/n]"

#: ../kde/apport-kde.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../gtk/apport-gtk.desktop.in.h:1
msgid "Report a problem..."
msgstr "Tilkynna vandamál..."

#: ../kde/apport-kde.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../gtk/apport-gtk.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Tilkynna bilun til forritara"

#: ../data/kernel_oops.py:28
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""
"Kerfið þitt verður kannski óstöðugt núna og þarf hugsanlega að endurræsa það."

#: ../gtk/apport-gtk.py:153
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "Því miður, forritið %s hætti óvænt."

#: ../gtk/apport-gtk.py:156
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "Því miður, forritið %s lokaði óvænt."

#: ../gtk/apport-gtk.py:161 ../kde/apport-kde.py:176 ../kde/apport-kde.py:217
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "Því miður, %s hefur lent í innri villu."

#: ../gtk/apport-gtk.py:182 ../kde/apport-kde.py:170
msgid "Send"
msgstr "Senda"

#: ../gtk/apport-gtk.py:200 ../gtk/apport-gtk.py:569 ../kde/apport-kde.py:271
#: ../gtk/apport-gtk.ui.h:7
msgid "Show Details"
msgstr "Sýna ítarlegri upplýsingar"

#: ../gtk/apport-gtk.py:212 ../gtk/apport-gtk.py:280 ../gtk/apport-gtk.py:299
#: ../kde/apport-kde.py:210 ../kde/apport-kde.py:223 ../gtk/apport-gtk.ui.h:10
msgid "Continue"
msgstr "Áfram"

#: ../gtk/apport-gtk.py:224
msgid "Force Closed"
msgstr "Þvinga til að loka"

#: ../gtk/apport-gtk.py:225 ../gtk/apport-gtk.py:284 ../kde/apport-kde.py:214
#: ../kde/apport-kde.py:357
msgid "Relaunch"
msgstr "Keyra aftur upp"

#: ../gtk/apport-gtk.py:234
#, python-format
msgid "The application %s has stopped responding."
msgstr "Forritið %s hætti að svara."

#: ../gtk/apport-gtk.py:238
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "Forritið %s hætti að svara."

#: ../gtk/apport-gtk.py:253 ../kde/apport-kde.py:184
#, python-format
msgid "Package: %s"
msgstr "Pakki: %s"

#: ../gtk/apport-gtk.py:260 ../kde/apport-kde.py:190
msgid "Sorry, a problem occurred while installing software."
msgstr "Því miður, vandamál kom upp við upppsetningu hugbúnaðar."

#: ../gtk/apport-gtk.py:269 ../gtk/apport-gtk.py:288 ../kde/apport-kde.py:197
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "Forritið %s lenti í innri villu."

#: ../gtk/apport-gtk.py:272 ../kde/apport-kde.py:201
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "Forritið %s lokaði óvænt."

#: ../gtk/apport-gtk.py:283 ../kde/apport-kde.py:213 ../gtk/apport-gtk.ui.h:9
msgid "Leave Closed"
msgstr "Skilja eftir lokað"

#: ../gtk/apport-gtk.py:296 ../kde/apport-kde.py:220 ../gtk/apport-gtk.ui.h:4
msgid "If you notice further problems, try restarting the computer."
msgstr "Ef þú verður var við fleiri vandamál, reyndu þá að endurræsa tölvuna."

#: ../gtk/apport-gtk.py:300 ../kde/apport-kde.py:224
msgid "Ignore future problems of this type"
msgstr "Hunsa svona vandamál héðan í frá"

#: ../gtk/apport-gtk.py:573 ../kde/apport-kde.py:268
msgid "Hide Details"
msgstr "Fela nánari upplýsingar"

#: ../bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "Sjá nánar á man-síðu."

#: ../bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr ""

#: ../bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""
"endurnýta sandkassamöppu (SDIR) sem þegar hefur verið búin til eða, ef hún "
"er ekki til, búa hana til"

#: ../bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""
"ekki búa til né endurnýta sandkassamöppu fyrir auka aflúsunarmerki heldur "
"aðeins treysta á uppsett aflúsunarmerki."

#: ../bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""
"endurnýta skyndiminnismöppu (CDIR) sem þegar hefur verið búin til eða, ef "
"hún er ekki til, búa hana til"

#: ../bin/apport-valgrind.py:58
msgid "report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""

#: ../bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "Villa: %s er ekki keyranlegt forrit. Hætti."

#: ../kde/apport-kde.py:294
msgid "Username:"
msgstr "Notandanafn:"

#: ../kde/apport-kde.py:295
msgid "Password:"
msgstr "Lykilorð:"

#: ../kde/apport-kde.py:382
msgid "Collecting Problem Information"
msgstr "Safna saman upplýsingum um vandamál"

#: ../kde/apport-kde.py:384
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"Söfnuðum upplýsingum er hægt að koma til forritaranna til að bæta forritið. "
"Þetta gæti tekið nokkrar mínútur."

#: ../kde/apport-kde.py:410
msgid "Uploading Problem Information"
msgstr "Sendi upplýsingar um vandamálið"

#: ../kde/apport-kde.py:412 ../gtk/apport-gtk.ui.h:15
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Er að senda upplýsingarnar á villukerfið. Þetta gæti tekið nokkrar mínútur."

#: ../kde/apport-kde.py:446 ../kde/apport-kde.py:482 ../gtk/apport-gtk.ui.h:1
msgid "Apport"
msgstr "Apport"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Safna kerfisupplýsingum"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"Auðkenningar er krafist fyrir söfnun á kerfisupplýsingum fyrir þessa "
"villuskýrslu"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "Vandamálaskýrslur kerfis"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid "Please enter your password to access problem reports of system programs"
msgstr "Sláðu inn lykilorð til að fá aðgang að villuskýrslum kerfisforrita"

#: ../gtk/apport-gtk.ui.h:2
msgid "Crash report"
msgstr "Hrunskýrsla"

#: ../gtk/apport-gtk.ui.h:3
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>Því miður, upp kom innri villa.</b></big>"

#: ../gtk/apport-gtk.ui.h:5
msgid "Send an error report to help fix this problem"
msgstr "Senda villuskýrslu til að hjálpa til við lausn þessa vandamáls"

#: ../gtk/apport-gtk.ui.h:6
msgid "Ignore future problems of this program version"
msgstr "Hunsa frekari vandamál í þessarri útgáfu forrits"

#: ../gtk/apport-gtk.ui.h:8
msgid "_Examine locally"
msgstr "Skoða _hér"

#: ../gtk/apport-gtk.ui.h:11
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Safna upplýsingum um vandamál</b></big>"

#: ../gtk/apport-gtk.ui.h:12
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"Er að safna upplýsingum sem gætu hjálpað forriturum að laga vandann sem þú "
"tilkynnir"

#: ../gtk/apport-gtk.ui.h:14
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Sendi vandamálsskýrslu</b></big>"

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Apport villuskrá"

#: ../bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "Notkun: %s <report> <target directory>"

#: ../bin/apport-unpack.py:46
msgid "Destination directory exists and is not empty."
msgstr ""

#~ msgid "Complete report (recommended; %s)"
#~ msgstr "Full skýrsla (mælt með; %s)"

#~ msgid ""
#~ "<big><b>Send problem report to the developers?</b></big>\n"
#~ "\n"
#~ "After the problem report has been sent, please fill out the form in the "
#~ "automatically opened web browser."
#~ msgstr ""
#~ "<big><b>Senda vandamálsskýrslu til forritaranna?</b></big>\n"
#~ "\n"
#~ "Eftir að skýrslan hefur verið send, vinsamlegast fylltu út formið í "
#~ "vafranum sem opnast sjálfkrafa."

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other "
#~ "private information), you can help to improve the application by "
#~ "reporting the problem."
#~ msgstr ""
#~ "Ef þú varst ekki að gera eitthvað leynilegt (slá inn lykilorð eða aðrar "
#~ "persónulegar upplýsingar) geturðu hjálpað við að bæta forritið með því að "
#~ "tilkynna vandamálið."

#~ msgid "Application problem"
#~ msgstr "Forritsvandamál"

#~ msgid "_Send Report"
#~ msgstr "_Senda skýrslu"

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other\n"
#~ "private information), you can help to improve the application by "
#~ "reporting\n"
#~ "the problem."
#~ msgstr ""
#~ "Ef þú varst ekki að gera eitthvað persónugreinanlegt (slá inn lykilorð "
#~ "eða \n"
#~ "aðrar persónulegar upplýsingar) getur þú hjálpað við að laga forritið "
#~ "með\n"
#~ "því að tilkynna vandamálið."

#~ msgid "Restart _Program"
#~ msgstr "_Endurræsa Forrit"

#~ msgid ""
#~ "<span weight=\"bold\" size=\"larger\">Sorry, the package \"%s\" failed to "
#~ "install or upgrade.</span>"
#~ msgstr ""
#~ "<span weight=\"bold\" size=\"larger\">Því miður tókst ekki að setja upp "
#~ "eða uppfæra pakkann \"%s\"</span>"

#~ msgid "Reduced report (slow Internet connection; %s)"
#~ msgstr "Minnkuð skýrsla (hæg nettenging; %s)"

#~ msgid "_Ignore future crashes of this program version"
#~ msgstr "_Hunsa frekari hrun þessarar forritsútgáfu"

#~ msgid ""
#~ "This will remove some large items from the report. These are very useful "
#~ "for developers to debug the problem, but might be too big for you to "
#~ "upload if you have a slow internet connection."
#~ msgstr ""
#~ "Þetta tekur nokkra stóra hluta úr skýrslunni. Þeir eru gagnlegir "
#~ "forriturum til að greina vandamálkið, en gætu verið of stórir til að að "
#~ "senda yfir hæga nettengingu."

#~ msgid "&Report Problem..."
#~ msgstr "&Tilkynna vandamál"

#~ msgid "_Report Problem..."
#~ msgstr "_Tilkynna vandamál..."

#~ msgid "Kernel problem"
#~ msgstr "Kjarnavandi"

#~ msgid ""
#~ "You can help the developers to fix the package by reporting the problem."
#~ msgstr ""
#~ "Þú getur hjálpað forriturunum að laga pakkann með því að senda inn "
#~ "tilkynningu."

#~ msgid "This is not a genuine %s package"
#~ msgstr "Þetta er ekki alvöru %s pakki"

#~ msgid "Content of the report"
#~ msgstr "Innihald skýrslunnar"

#~ msgid "Package problem"
#~ msgstr "Pakkavandamál"

#~ msgid "The package \"%s\" failed to install or upgrade."
#~ msgstr "Það tókst hvorki að setja upp “%s“ eða uppfæra."

#~ msgid "%s closed unexpectedly on %s at %s."
#~ msgstr "%s lokaði óviðbúið þann %s klukkan %s."

#~ msgid "Your system encountered a serious kernel problem."
#~ msgstr "Kerfið þitt lenti í alvarlegum vanda með stýrikerfiskjarnann"

#~ msgid "You can help the developers to fix the problem by reporting it."
#~ msgstr "Þú getur hjálpað til með því að tilkynna vandann."

#~ msgid "&Send complete report (recommended; %s)"
#~ msgstr "&Senda alla skýrsluna (mælt með þessu; %s)"

#~ msgid "Send &reduced report (slow Internet connection; %s)"
#~ msgstr "Senda &stytta skýrslu (hæg nettenging; %s)"
