# Uighur translation for apport
# Copyright (c) 2009 Rosetta Contributors and Canonical Ltd 2009
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2009.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-09-10 11:16+0200\n"
"PO-Revision-Date: 2015-04-27 21:46+0000\n"
"Last-Translator: bilgeturghun <bilgeks@gmail.com>\n"
"Language-Team: Uighur <ug@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2018-10-06 05:28+0000\n"
"X-Generator: Launchpad (build 18785)\n"
"Language: ug\n"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1
#: ../debian/tmp/usr/share/apport/apport-kde.py:469
#: ../debian/tmp/usr/share/apport/apport-kde.py:504
#: ../debian/tmp/usr/share/apport/apport-kde.py:524 ../gtk/apport-gtk.ui.h:1
#: ../kde/apport-kde.py:469 ../kde/apport-kde.py:504 ../kde/apport-kde.py:524
msgid "Apport"
msgstr "Apport"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2 ../gtk/apport-gtk.ui.h:2
msgid "Cancel"
msgstr "ئەمەلدىن قالدۇر"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3 ../gtk/apport-gtk.ui.h:3
msgid "OK"
msgstr "تامام"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4 ../gtk/apport-gtk.ui.h:4
msgid "Crash report"
msgstr "يىمىرىلىش دوكلاتى"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5 ../gtk/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>كەچۈرۈڭ، ئىچكى خاتالىق يۈز بەردى.</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
#: ../debian/tmp/usr/share/apport/apport-kde.py:241 ../gtk/apport-gtk.py:297
#: ../gtk/apport-gtk.ui.h:7 ../debian/tmp/usr/share/apport/apport-gtk.py:297
#: ../kde/apport-kde.py:241
msgid "If you notice further problems, try restarting the computer."
msgstr ""
"ئەگەر تېخىمۇ كۆپ مەسىلىنى بايقىسىڭىز، كومپيۇتېرنى قايتا قوزغىتىشنى سىناڭ."

#: ../gtk/apport-gtk.ui.h:7 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
msgid "Send an error report to help fix this problem"
msgstr ""
"بۇ مەسىلىنى ئوڭلاشقا ياردەم قىلىش ئۈچۈن خاتالىق دوكلاتىدىن بىرنى يوللاڭ"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9 ../gtk/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr "بۇ پروگرامما نەشرىنىڭ كەلگۈسىدىكى مەسىلىلىرىگە پەرۋا قىلما"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
#: ../debian/tmp/usr/share/apport/apport-kde.py:292 ../gtk/apport-gtk.py:204
#: ../gtk/apport-gtk.py:575 ../gtk/apport-gtk.ui.h:11
#: ../debian/tmp/usr/share/apport/apport-gtk.py:204
#: ../debian/tmp/usr/share/apport/apport-gtk.py:575 ../kde/apport-kde.py:292
msgid "Show Details"
msgstr "تەپسىلاتلارنى كۆرسەت"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12 ../gtk/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr "يەرلىكتە تەكشۈر(_E)"

#: ../debian/tmp/usr/share/apport/apport-kde.py:234 ../kde/apport-kde.py:234
msgid "Leave Closed"
msgstr "تاقاق پېتى قالدۇر"

#: ../debian/tmp/usr/share/apport/apport-kde.py:231
#: ../debian/tmp/usr/share/apport/apport-kde.py:244 ../gtk/apport-gtk.py:216
#: ../debian/tmp/usr/share/apport/apport-gtk.py:216 ../kde/apport-kde.py:231
#: ../kde/apport-kde.py:244
msgid "Continue"
msgstr "داۋاملاشتۇر"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15 ../gtk/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>مەسىلە ھەققىدە ئۇچۇرلارنى توپلاۋاتىدۇ</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:16 ../gtk/apport-gtk.ui.h:16
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"سىز مەلۇم قىلغان مەسىلىنى ئىجادىيەتچىلەرنىڭ تۈزىتىشىگە ياردىمى بولسۇن دەپ "
"ئۇچۇرلار توپلاندى."

#: ../bin/apport-cli.py:267 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:17
#: ../debian/tmp/usr/share/apport/apport-kde.py:435 ../gtk/apport-gtk.ui.h:17
#: ../kde/apport-kde.py:435 ../debian/tmp/usr/bin/apport-cli.py:267
msgid "Uploading problem information"
msgstr "مەسىلىلەر ھەققىدىكى ئۇچۇرلارنى يېڭىلاۋاتىدۇ"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:18 ../gtk/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>مەسىلە ھەققىدىكى ئۇچۇرلارنى يۈكلەۋاتىدۇ</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:19
#: ../debian/tmp/usr/share/apport/apport-kde.py:436 ../gtk/apport-gtk.ui.h:19
#: ../kde/apport-kde.py:436
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"توپلانغان ئۇچۇرلارنى كەمتۈك باشقۇرۇش سىستېمىسىغا ئەۋەتمەكچى. بۇنىڭغا ئازراق "
"ۋاقىت كېتىدۇ."

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Apport چاتاق ھۆججىتى"

#: ../bin/apport-cli.py:166 ../debian/tmp/usr/share/apport/apport-kde.py:363
#: ../gtk/apport-gtk.py:146 ../debian/tmp/usr/share/apport/apport-gtk.py:146
#: ../kde/apport-kde.py:363 ../debian/tmp/usr/bin/apport-cli.py:166
msgid "(binary data)"
msgstr "(ئىككىلىك سانلىق-مەلۇمات)"

#: ../gtk/apport-gtk.py:161 ../debian/tmp/usr/share/apport/apport-gtk.py:161
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "كەچۈرۈڭ، پروگرامما %s  تاسادىپىي توختاپ قالدى."

#: ../gtk/apport-gtk.py:164 ../debian/tmp/usr/share/apport/apport-gtk.py:164
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "كەچۈرۈڭ، %s تاسادىپىي تاقالدى."

#: ../debian/tmp/usr/share/apport/apport-kde.py:200
#: ../debian/tmp/usr/share/apport/apport-kde.py:238 ../gtk/apport-gtk.py:169
#: ../debian/tmp/usr/share/apport/apport-gtk.py:169 ../kde/apport-kde.py:200
#: ../kde/apport-kde.py:238
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "كەچۈرۈڭ، %s ئىچكى خاتالىققا يولۇقتى."

#: ../bin/apport-cli.py:194 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
#: ../debian/tmp/usr/share/apport/apport-kde.py:186 ../gtk/apport-gtk.py:181
#: ../gtk/apport-gtk.ui.h:6 ../debian/tmp/usr/share/apport/apport-gtk.py:181
#: ../kde/apport-kde.py:186 ../debian/tmp/usr/bin/apport-cli.py:194
msgid "Send problem report to the developers?"
msgstr "بۇ مەلۇماتنى ئىجادىيەتچىگە ئەۋەتسۇنمۇ؟"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14
#: ../debian/tmp/usr/share/apport/apport-kde.py:194 ../gtk/apport-gtk.py:188
#: ../gtk/apport-gtk.ui.h:14 ../debian/tmp/usr/share/apport/apport-gtk.py:188
#: ../kde/apport-kde.py:194
msgid "Send"
msgstr "يوللا"

#: ../gtk/apport-gtk.py:231 ../debian/tmp/usr/share/apport/apport-gtk.py:231
msgid "Force Closed"
msgstr "مەجبۇرىي يېپىلغان"

#: ../debian/tmp/usr/share/apport/apport-kde.py:235
#: ../debian/tmp/usr/share/apport/apport-kde.py:381 ../kde/apport-kde.py:235
#: ../kde/apport-kde.py:381
msgid "Relaunch"
msgstr "قايتا ئىجرا قىل"

#: ../gtk/apport-gtk.py:239 ../debian/tmp/usr/share/apport/apport-gtk.py:239
#, python-format
msgid "The application %s has stopped responding."
msgstr "پروگرامما %s جاۋاب قايتۇرۇشتىن توختىدى."

#: ../gtk/apport-gtk.py:243 ../debian/tmp/usr/share/apport/apport-gtk.py:243
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "پروگرامما «%s» جاۋاب قايتۇرۇشتىن توختىدى."

#: ../debian/tmp/usr/share/apport/apport-kde.py:208 ../gtk/apport-gtk.py:259
#: ../debian/tmp/usr/share/apport/apport-gtk.py:259 ../kde/apport-kde.py:208
#, python-format
msgid "Package: %s"
msgstr "بوغچا: %s"

#: ../debian/tmp/usr/share/apport/apport-kde.py:214 ../gtk/apport-gtk.py:265
#: ../debian/tmp/usr/share/apport/apport-gtk.py:265 ../kde/apport-kde.py:214
msgid "Sorry, a problem occurred while installing software."
msgstr "كەچۈرۈڭ، يۇمشاق دېتال ئورناتقاندا بىر خاتالىق كۆرۈلدى."

#: ../debian/tmp/usr/share/apport/apport-kde.py:220 ../gtk/apport-gtk.py:274
#: ../gtk/apport-gtk.py:289 ../debian/tmp/usr/share/apport/apport-gtk.py:274
#: ../debian/tmp/usr/share/apport/apport-gtk.py:289 ../kde/apport-kde.py:220
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "پروگرامما %s نىڭدا بىر ئىچكى خاتالىق يۈز بەردى."

#: ../debian/tmp/usr/share/apport/apport-kde.py:223 ../gtk/apport-gtk.py:277
#: ../debian/tmp/usr/share/apport/apport-gtk.py:277 ../kde/apport-kde.py:223
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "بۇ %s ئەپ تاسادىپىي تاقالدى."

#: ../debian/tmp/usr/share/apport/apport-kde.py:245 ../gtk/apport-gtk.py:299
#: ../debian/tmp/usr/share/apport/apport-gtk.py:299 ../kde/apport-kde.py:245
msgid "Ignore future problems of this type"
msgstr "بۇ تۈردىكى كەلگۈسىدىكى مەسىلىگە سەل قاراش"

#: ../debian/tmp/usr/share/apport/apport-kde.py:289 ../gtk/apport-gtk.py:579
#: ../debian/tmp/usr/share/apport/apport-gtk.py:579 ../kde/apport-kde.py:289
msgid "Hide Details"
msgstr "تەپسىلاتلارنى يوشۇر"

#: ../bin/apport-unpack.py:22 ../debian/tmp/usr/bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "ئىشلىتىش ئۇسۇلى: %s <مەلۇمات> <نىشان مۇندەرىجە>"

#: ../bin/apport-unpack.py:47 ../debian/tmp/usr/bin/apport-unpack.py:47
msgid "Destination directory exists and is not empty."
msgstr "نىشان مۇندەرىجە بار ھەم بوش ئەمەس."

#: ../debian/tmp/usr/share/apport/apport-kde.py:315 ../kde/apport-kde.py:315
msgid "Username:"
msgstr "ئىشلەتكۈچى ئاتى:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:316 ../kde/apport-kde.py:316
msgid "Password:"
msgstr "ئىم:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:406 ../kde/apport-kde.py:406
msgid "Collecting Problem Information"
msgstr "چاتاق ھەققىدىكى ئۇچۇرلارنى توپلاۋاتىدۇ"

#: ../bin/apport-cli.py:254 ../debian/tmp/usr/share/apport/apport-kde.py:407
#: ../kde/apport-kde.py:407 ../debian/tmp/usr/bin/apport-cli.py:254
msgid "Collecting problem information"
msgstr "مەسىلىلەرگە ئائىت ئۇچۇرلارنى توپلاۋاتىدۇ"

#: ../debian/tmp/usr/share/apport/apport-kde.py:408 ../kde/apport-kde.py:408
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"ئىجادىيەتچىنىڭ پروگرامما ئىقتىدارىنى ياخشىلىشىغا قۇلايلىق يارىتىش ئۈچۈن، "
"توپلانغان ئۇچۇرلار ئىجادىيەتچىگە يوللىنىدۇ. بۇنىڭغا بىرقانچە مىنۇت كېتىدۇ."

#: ../debian/tmp/usr/share/apport/apport-kde.py:434 ../kde/apport-kde.py:434
msgid "Uploading Problem Information"
msgstr "چاتاق ھەققىدىكى ئۇچۇرلارنى يۈكلەۋاتىدۇ"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "سىستېما ئۇچۇرلىرىنى توپلا"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"بۇ مەسىلىنى مەلۇم قىلىشتا سىستېما ئۇچۇرلىرىنى توپلاش كېرەك، بىراق بۇنىڭ "
"ئۈچۈن كىملىك دەلىللەش زۆرۈردۇر."

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "سىستېما مەسىلە دوكلاتى"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid ""
"Please enter your password to access problem reports of system programs"
msgstr "ئىمنى كىرگۈزۈپ سىستېما مەسىلە دوكلاتىنى كۆرۈڭ."

#: ../kde/apport-kde.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../gtk/apport-gtk.desktop.in.h:1
msgid "Report a problem..."
msgstr "مەسىلىنى مەلۇم قىلىش..."

#: ../kde/apport-kde.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../gtk/apport-gtk.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "خاتالىقنى ئىجادىيەتچىگە مەلۇم قىلىدۇ"

#: ../bin/apport-valgrind.py:37 ../debian/tmp/usr/bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "تېخىمۇ كۆپ تەپسىلاتنى man قوللانمىسىدىن كۆرۈڭ."

#: ../bin/apport-valgrind.py:43 ../debian/tmp/usr/bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr "بۇ valgrind ھاسىل قىلىدىغان خاتىرە ھۆججىتىنىڭ ئىسمىنى بەلگىلەڭ."

#: ../bin/apport-valgrind.py:46 ../debian/tmp/usr/bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""
"ئىلگىرى قۇرۇلغان sandbox مۇندەرىجىسى (SDIR) نى قايتا ئىشلىتىدۇ ياكى ئەگەر ئۇ "
"مەۋجۇت بولمىسا، ئۇنى قۇرىدۇ"

#: ../bin/apport-valgrind.py:50 ../debian/tmp/usr/bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""
"قوشۇمچە سازلاش بەلگىسى ئۈچۈن sandbox مۇندەرىجىسىنى قۇرمايدۇ ياكى قايتا "
"ئىشلەتمەيدۇ ئەمما پەقەت ئورنىتىلغان سازلاش بەلگىلىرىگە تايىنىدۇ."

#: ../bin/apport-valgrind.py:54 ../debian/tmp/usr/bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""
"ئىلگىرى قۇرۇلغان غەملەك مۇندەرىجە (CDIR) نى قايتا ئىشلىتىدۇ ياكى ئەگەر "
"مەۋجۇت بولمىسا ئۇنى قۇرىدۇ"

#: ../bin/apport-valgrind.py:58 ../debian/tmp/usr/bin/apport-valgrind.py:58
msgid ""
"report download/install progress when installing packages into sandbox"
msgstr ""
"ئورنىتىش بوغچىسى sandbox قا كىرسە چۈشۈرۈش/ئورنىتىش جەريانىنى دوكلات قىلىدۇ"

#: ../bin/apport-valgrind.py:62 ../debian/tmp/usr/bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""
"ئەسلەك ھالقىشنى بايقاش ئۈچۈن ئىجراچان پىروگراممىلار valgrind ئەسلەك تەكشۈرۈش "
"قورالىنىڭ ئاستىدا ئىجرا قىلىنىدۇ"

#: ../bin/apport-valgrind.py:66 ../debian/tmp/usr/bin/apport-valgrind.py:66
#: ../bin/apport-retrace.py:65 ../debian/tmp/usr/bin/apport-retrace.py:65
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""
"قۇم خالتىسى ئىچىگە قوشۇمچە بوغچىنى ئورنىتىش(بىر قانچە قېتىم كۆرسىتىشكە "
"بولىدۇ)"

#: ../bin/apport-valgrind.py:97 ../debian/tmp/usr/bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "خاتالىق: %s نى ئىجرا قىلغىلى بولمايدۇ. توختىتىۋاتىدۇ."

#: ../data/kernel_oops.py:29 ../debian/tmp/usr/share/apport/kernel_oops.py:29
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""
"سىستېمىڭىزنىڭ تۇراقسىز بولۇپ قېلىش ئېھتىماللىقى بار، قايتا قوزغىتىش "
"زۆرۈرىيىتى باردەك قىلىدۇ."

#: ../bin/apport-retrace.py:34 ../debian/tmp/usr/bin/apport-retrace.py:34
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr "بۇ يېڭى چىققانلىرىنى مەلۇماتقا يازماي stdout قا يازسۇن."

#: ../bin/apport-retrace.py:36 ../debian/tmp/usr/bin/apport-retrace.py:36
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""
"مەلۇماتنىڭ غول تۆكمىسىگە نىسبەتەن تەسىرلىشىشچان gdb ئەڭگىمەسىنى باشلايدۇ(-o "
"غا پەرۋا قىلمايدۇ؛ مەلۇماتنى قاپلىمايدۇ)"

#: ../bin/apport-retrace.py:38 ../debian/tmp/usr/bin/apport-retrace.py:38
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr "ئەسلىدىكى مەلۇماتقا يازماي كۆرسىتىلگەن ھۆججەتكە يازسۇن."

#: ../bin/apport-retrace.py:41 ../debian/tmp/usr/bin/apport-retrace.py:41
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""
"stack ئىزلىشى قايتا ھاسىللانغاندىن كېيىن، غول تۆكمىنى(core dump) مەلۇماتتىن "
"چىقىرىۋېتىش"

#: ../bin/apport-retrace.py:43 ../debian/tmp/usr/bin/apport-retrace.py:43
msgid "Override report's CoreFile"
msgstr "دوكلاتنىڭ CoreFile نى قاپلاش"

#: ../bin/apport-retrace.py:45 ../debian/tmp/usr/bin/apport-retrace.py:45
msgid "Override report's ExecutablePath"
msgstr "دوكلاتنىڭ ExecutablePath نى قاپلاش"

#: ../bin/apport-retrace.py:47 ../debian/tmp/usr/bin/apport-retrace.py:47
msgid "Override report's ProcMaps"
msgstr "دوكلاتنىڭ ProcMaps نى قاپلاش"

#: ../bin/apport-retrace.py:49 ../debian/tmp/usr/bin/apport-retrace.py:49
msgid "Rebuild report's Package information"
msgstr "دوكلاتنىڭ بوغچا ئۇچۇرىنى قايتا قۇرۇش"

#: ../bin/apport-retrace.py:51 ../debian/tmp/usr/bin/apport-retrace.py:51
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""
"ۋاقتىنچە قۇم ساندۇقى قۇرىدۇ ھەم قاچىلاش بوغچىسىنى يۈكلەيدۇ/قاچىلايدۇ.ئەگەر "
"بۇ تاللانما ئىشلىتىلمىسە، سىستېمىغا لازىملىق دېتالنى قاچىلايدۇ. ئەگەر سىز "
"سىستېما بەلگىلىمىسىڭىز، سىستېما سەپلىمىسىنى ئىشلىتىدۇ، شۇنىڭ بىلەن ئىجرا "
"قىلىنىۋاتقان سىستېمىنى ھالاك قىلىدۇ."

#: ../bin/apport-retrace.py:55 ../debian/tmp/usr/bin/apport-retrace.py:55
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""
"بوغچىلارنى قۇم خالتىسى ئىچىگە ئورناتقاندىكى چۈشۈرۈش/ئورنىتىش جەريانىنى مەلۇم "
"قىلىش"

#: ../bin/apport-retrace.py:57 ../debian/tmp/usr/bin/apport-retrace.py:57
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""
"ئۇچۇر خاتىرىلەشتىن بۇرۇن ۋاقىتنى خاتىرىلەڭ، بۇ قېتىملىق مەشغۇلاتنى "
"تەمىنلەيدۇ."

#: ../bin/apport-retrace.py:59 ../debian/tmp/usr/bin/apport-retrace.py:59
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr ""
"دوكلاتتا كۆرسىتىلگەن ئەسلى ئورۇندىن پايدىلىنىپ ئۈچىنچى تەرەپ خەزىنىسىنى "
"ياسايدۇ ۋە ئىشلىتىدۇ."

#: ../bin/apport-retrace.py:61 ../debian/tmp/usr/bin/apport-retrace.py:61
msgid "Cache directory for packages downloaded in the sandbox"
msgstr "قۇم خالتىسى ئىچىگە چۈشۈرۈلگەن بوغچىلارنىڭ غەملەك مۇندەرىجىسى"

#: ../bin/apport-retrace.py:63 ../debian/tmp/usr/bin/apport-retrace.py:63
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""
"يېيىلمىغان بوغچىلارنىڭ مۇندەرىجىسى. كېيىن ئىجرا قىلىدىغان چاغدا، چۈشۈرۈلگەن "
"بوغچىلار مۇشۇ يەرگە يېيىلىدۇ."

#: ../bin/apport-retrace.py:67 ../debian/tmp/usr/bin/apport-retrace.py:67
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"يىمىرىلىش ساندانىنى زىيارەت قىلىش ئۇچۇرى ھۆججىتىنىڭ يولىنى ئۆز ئىچىگە "
"ئالىدۇ. بۇ تاللانما مۇئەييەن يىمىرىلىش كودىدا  ئىزلاشنىڭ قايتۇرما سازلاش "
"ئۇچۇرى ئۈچۈن ئىشلىتىلىدۇ. (ئىشلەتكۈچى -g, -o, ياكى -s نى بەلگىلىگەن "
"بولمىسىلا)"

#: ../bin/apport-retrace.py:69 ../debian/tmp/usr/bin/apport-retrace.py:69
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""
"قايتۇرغان ئىزلاش ئۇچۇرىنى كۆرسىتىدۇ ھەمدە يىمىرىلىش ساندىنىغا يوللاش "
"يوللىماسلىقنى جەزملەشنى سورايدۇ."

#: ../bin/apport-retrace.py:71 ../debian/tmp/usr/bin/apport-retrace.py:71
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""
"تەكرارلانغان sqlite ساندىنىنىڭ يولى.(كۆڭۈلدە تەكرارلىنىشنى تەكشۈرمەيدۇ)"

#: ../bin/apport-retrace.py:82 ../debian/tmp/usr/bin/apport-retrace.py:82
msgid "You cannot use -C without -S. Stopping."
msgstr ""
"سىز -S نى بەلگىلىمەي تۇرۇپ -C تاللانمىنى ئىشلىتەلمەيسىز، توختىتىۋاتىدۇ."

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../bin/apport-retrace.py:115 ../debian/tmp/usr/bin/apport-retrace.py:115
msgid "OK to send these as attachments? [y/n]"
msgstr "بۇ قوشۇلما ھۆججەتلەرنى ئەۋەتسە بولامدۇ؟[y/n]"

#: ../apport/ui.py:144
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:144
msgid "This package does not seem to be installed correctly"
msgstr "مەزكۇر بوغچا توغرا ئورنىتىلمىغاندەك قىلىدۇ"

#: ../apport/ui.py:149
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:149
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""
"بۇ رەسمىي %s بوغچىسى ئەمەس. ئۈچىنچى تەرەپ بوغچىسىنى چىقىرىۋېتىپ، قايتا سىناڭ."

#: ../apport/ui.py:166
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:166
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"بەزىبىر كونا بوغچىلار بار ئىكەن. تۆۋەندىكى بوغچىلارنى يۈكسەلدۈرگەندىن كېيىن "
"يەنە تەكشۈرۈپ كۆرۈڭ:\n"
"\n"
"%s"

#: ../apport/ui.py:296
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:296
msgid "unknown program"
msgstr "نامەلۇم پروگرامما"

#: ../apport/ui.py:297
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:297
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "كەچۈرۈڭ، پروگرامما  «%s» ئويلىمىغان يەردىن تاقىلىپ قالدى"

#: ../apport/ui.py:299 ../apport/ui.py:1388
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:299
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1388
#, python-format
msgid "Problem in %s"
msgstr "مەسىلە %s نىڭدا"

#: ../apport/ui.py:300
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:300
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"مەسىلىنى ئاپتوماتىك ئانالىز قىلىش ۋە ئىجادىيەتچىگە مەلۇمات يوللاشقا كېرەكلىك "
"ئەسلەك يېتەرلىك ئەمەس ئىكەن."

#: ../apport/ui.py:355 ../apport/ui.py:363 ../apport/ui.py:490
#: ../apport/ui.py:493 ../apport/ui.py:693 ../apport/ui.py:1194
#: ../apport/ui.py:1360 ../apport/ui.py:1364
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:355
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:363
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:490
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:493
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:693
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1194
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1360
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1364
msgid "Invalid problem report"
msgstr "مەلۇمات ئىناۋەتسىز"

#: ../apport/ui.py:356
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:356
msgid "You are not allowed to access this problem report."
msgstr "بۇ مەسىلىنى مەلۇم قىلىش ھوقۇقىڭىز يوق."

#: ../apport/ui.py:359
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:359
msgid "Error"
msgstr "خاتالىق"

#: ../apport/ui.py:360
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:360
msgid "There is not enough disk space available to process this report."
msgstr "مەزكۇر مەلۇماتنى بىر تەرەپ قىلىشقا كېرەكلىك دىسكا بوشلۇقى يوق."

#: ../apport/ui.py:444
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:444
msgid "No package specified"
msgstr "بوغچا كۆرسىتىلمىگەن."

#: ../apport/ui.py:445
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:445
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"بوغچا ياكى بىر PID نى كۆرسىتىڭ. تەپسىلاتلار ئۈچۈن --help نى ئىشلىتىڭ."

#: ../apport/ui.py:468
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:468
msgid "Permission denied"
msgstr "ھوقۇقىڭىز يەتمىدى"

#: ../apport/ui.py:469
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:469
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"بۇ سىزنىڭ پروگراممىڭىز ئەمەس. مەزكۇر پروگراممىنى ئۆزىڭىزنىڭ ياكى root نىڭ "
"ھوقۇقىدا ئىجرا قىلدۇرۇڭ."

#: ../apport/ui.py:471
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:471
msgid "Invalid PID"
msgstr "ئىناۋەتسىز PID"

#: ../apport/ui.py:472
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:472
msgid "The specified process ID does not belong to a program."
msgstr "كۆرسىتىلگەن PID مەزكۇر پروگراممىنىڭ PID ئەمەس."

#: ../apport/ui.py:491
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:491
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "ئەھۋال قوليازما %s تەسىر كۆرسىتىدىغان بوغچىنى بەلگىلىمىگەن"

#: ../apport/ui.py:494
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:494
#, python-format
msgid "Package %s does not exist"
msgstr "بوغچا %s مەۋجۇت ئەمەس"

#: ../apport/ui.py:518 ../apport/ui.py:705 ../apport/ui.py:710
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:518
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:705
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:710
msgid "Cannot create report"
msgstr "مەلۇمات قۇرالمىدى"

#: ../apport/ui.py:533 ../apport/ui.py:579 ../apport/ui.py:595
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:533
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:579
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:595
msgid "Updating problem report"
msgstr "مەلۇماتىنى يېڭىلاۋاتىدۇ"

#: ../apport/ui.py:534
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:534
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"سىز بۇ مەسىلىنى مەلۇم قىلغان كىشى ئەمەس، ياكى مەلۇمات تەكرارلانغان ياكى "
"ئاللىقاچان تاقالغان.\n"
"\n"
"«apport-bug» نى ئىشلىتىپ يېڭىدىن مەلۇمات تەييارلاڭ."

#: ../apport/ui.py:543
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:543
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"سىز بۇ مەسىلىنى مەلۇم قىلغۇچى ئەمەس. يېڭى كەمتۈك دەپ مەلۇم قىلغاندىن كۆرە، "
"باشقا كەمتۈك بىلەن ئوخشاش دەپ بەلگە قويۇش تېخىمۇ ئاسان.\n"
"\n"
"ئارقىدىن، «apport-bug» نى ئىشلىتىپ، كەمتۈك مەلۇم قىلىپ، مەلۇماتنىڭ ئىچىگە "
"كەمتۈك ھەققىدىكى ئىزاھاتنى يېزىشىڭىزنى تەۋسىيە قىلىمىز.\n"
"\n"
"راستلا داۋاملاشتۇرامسىز؟"

#: ../apport/ui.py:580 ../apport/ui.py:596
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:580
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:596
msgid "No additional information collected."
msgstr "قوشۇمچە ئۇچۇرلار توپلانمىدى."

#: ../apport/ui.py:647
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:647
msgid "What kind of problem do you want to report?"
msgstr "قانداق مەسىلىنى مەلۇم قىلماقچى؟"

#: ../apport/ui.py:664
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:664
msgid "Unknown symptom"
msgstr "نامەلۇم ھادىسە"

#: ../apport/ui.py:665
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:665
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "ھادىسە «%s» نامەلۇم."

#: ../apport/ui.py:696
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:696
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"ئۇچۇرنى ياپقاندىن كېيىن پروگرامما كۆزنىكىنى چېكىپ، بۇ مەسىلىنى مەلۇم قىلىڭ."

#: ../apport/ui.py:706 ../apport/ui.py:711
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:706
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:711
msgid "xprop failed to determine process ID of the window"
msgstr "xprop كۆزنەكنىڭ ئىجرا ID سىنى تېپىشتا مەغلۇپ بولدى"

#: ../apport/ui.py:725
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:725
msgid "%prog <report number>"
msgstr "%prog <مەلۇمات نومۇرى>"

#: ../apport/ui.py:727
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:727
msgid "Specify package name."
msgstr "بوغچا ئاتىنى كۆرسىتىپ بېرىڭ."

#: ../apport/ui.py:729 ../apport/ui.py:780
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:729
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:780
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr "دوكلاتقا يېڭىدىن خەتكۈش قوشۇڭ، كۆپ قېتىم بەلگىلەشكە بولىدۇ."

#: ../apport/ui.py:759
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:759
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"

#: ../apport/ui.py:762
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:762
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"كەمتۈك يېزىش ھالىتىدە باشلايدۇ. ئىجرا قىلغاندا --package ۋە --pid ياكى "
"پەقەتلا --pid تاللانمىسىنى يازسىلا بولىدۇ. ئەگەر ھېچقايسى يېزىلمىسا، "
"كۆرۈلگەن ئالامەتلەرنىڭ تىزىمىنى كۆرسىتىدۇ. (پەقەت يالغۇز ئارگۇمېنت "
"بېرىلگەندىلا.)"

#: ../apport/ui.py:764
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:764
msgid "Click a window as a target for filing a problem report."
msgstr "خاتالىق دوكلاتىنى تولدۇرۇش ئۈچۈن كۆزنەكنى نىشان قىلىپ چېكىڭ"

#: ../apport/ui.py:766
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:766
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""
"كەمتۈك يېڭىلاش ھالىتىدە قوزغىتىش. --package دېگەن تاللانمىنى ئىشلىتىشكە "
"بولىدۇ."

#: ../apport/ui.py:768
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:768
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""
"ھادىسە ھەققىدە مەلۇمات تەييارلاڭ. (Implied if symptom name is given as only "
"argument)"

#: ../apport/ui.py:770
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:770
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"--file-bug ھالىتىدە بوغچا ئاتىنى كۆرسىتىڭ. ئەگەر --pid كۆرسىتىلگەن بولسا، "
"بۇنى كۆرسەتمىسىمۇ بولىدۇ.(Implied if package name is given as only argument.)"

#: ../apport/ui.py:772
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:772
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""
"--file-bug  ھالىتىدە ئىجرا بولۇۋاتقان پروگراممىنى كۆرسىتىڭ. ئەگەر بۇ "
"كۆرسىتىلسە، كەمتۈك مەلۇماتىغا تېخىمۇ كۆپ ئۇچۇرلار قوشۇلىدۇ. (Implied if pid "
"is given as only argument.)"

#: ../apport/ui.py:774
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:774
msgid "The provided pid is a hanging application."
msgstr ""
"تەمىنلەنگەن pid بولسا بىر ئېسىلىپ قالغان(توختاپ قالغان) پروگرامما ئىكەن."

#: ../apport/ui.py:776
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:776
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"چاتاق مەلۇماتىنى  %s نىڭدىكى كۈتۈپ تۇرغان ھۆججەتنى ئەمەس بەلكى بېرىلگەن  "
".apport ياكى .crash ھۆججىتىنى ئىشلىتىپ يوللاش(پەقەت ھۆججەت ئاتى ئارگۇمېنت "
"شەكىلدە بېرىلگەندىلا.)"

#: ../apport/ui.py:778
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:778
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""
"كەمتۈك يېزىش ھالىتىدە، توپلانغان ئۇچۇرلارنى مەلۇم قىلماي ھۆججەتكە ساقلاپ "
"قويۇشقا، بۇ ھۆججەتنى كېيىن باشقا كومپيۇتېر ئارقىلىق يوللاشقىمۇ بولىدۇ."

#: ../apport/ui.py:782
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:782
msgid "Print the Apport version number."
msgstr "Apport نىڭ نەشر نومۇرىنى بېسىپ چىقىرىدۇ."

#: ../apport/ui.py:922
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:922
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""
"crash نى تەكشۈرۈش ئۈچۈن apport-retrace تېرمىنال كۆزنىكىدە ئىجرا بولىدۇ."

#: ../apport/ui.py:923
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:923
msgid "Run gdb session"
msgstr "gdb ئەڭگىمەسىنى ئىجرا قىلىش"

#: ../apport/ui.py:924
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:924
msgid "Run gdb session without downloading debug symbols"
msgstr "سازلاش بەلگىلىرىنى چۈشۈرمەيلا gdb ئەڭگىمەسىنى ئىجرا قىلىش"

#. TRANSLATORS: %s contains the crash report file name
#: ../apport/ui.py:926
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:926
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "%s نى تولۇق بەلگىلەر بىلەن يېڭىلاش"

#: ../apport/ui.py:1022 ../apport/ui.py:1032
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1022
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1032
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr "بۇ دوكلات زادىلا ئورنىتىلىپ باقمىغان پروگراممىغا ئىشلىتىلىدۇ."

#: ../apport/ui.py:1047
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1047
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr "توقۇنۇشتا ئۆزگەرگەن پروگرامما %s تە خاتالىق كۆرۈلدى."

#: ../apport/ui.py:1094 ../apport/ui.py:1151 ../apport/ui.py:1366
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1094
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1151
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1366
msgid "This problem report is damaged and cannot be processed."
msgstr "بوغچا بۇزۇلغان بولغاچقا بىر تەرەپ قىلغىلى بولمىدى."

#. package does not exist
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1051
#: ../apport/ui.py:1051
msgid "The report belongs to a package that is not installed."
msgstr "مەلۇمات ئورنىتىلمىغان بوغچىغا تەۋە ئىكەن."

#: ../apport/ui.py:1113
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1113
msgid "An error occurred while attempting to process this problem report:"
msgstr ""
"بۇ مەسىلە ھەققىدىكى مەلۇماتنى بىر تەرەپ قىلاي دېگەندە  خاتالىق يۈز بەردى:"

#: ../apport/ui.py:1195
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1195
msgid "Could not determine the package or source package name."
msgstr "بوغچا ياكى مەنبە كود بوغچىسىنىڭ نامىنى بېكىتكىلى بولمىدى."

#: ../apport/ui.py:1213
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1213
msgid "Unable to start web browser"
msgstr "توركۆرگۈنى قوزغاتقىلى بولمىدى"

#: ../apport/ui.py:1214
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1214
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "%s نى كۆرىدىغان توركۆرگۈنى قوزغاتقىلى بولمىدى."

#: ../apport/ui.py:1314
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1314
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr "كەمتۈك باشقۇرۇش سىستېمىسى %s غا ھېسابات ئۇچۇرىڭىزنى كىرگۈزۈڭ."

#: ../apport/ui.py:1326
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1326
msgid "Network problem"
msgstr "توردىكى مەسىلە"

#: ../apport/ui.py:1328
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1328
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr "crash ساندىنىغا باغلىنالمىدى، ئىنتېرنېت باغلىنىشىنى تەكشۈرۈپ كۆرۈڭ."

#: ../apport/ui.py:1355
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1355
msgid "Memory exhaustion"
msgstr "ئەسلەك يېتىشمىدى"

#: ../apport/ui.py:1356
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1356
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"سىستېمىڭىزدا مەزكۇر crash مەلۇماتىنى بىر تەرەپ قىلىشقا يېتەرلىك ئەسلەك يوق."

#: ../apport/ui.py:1391
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1391
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"مەسىلىنى مەلۇم قىلغىلى بولمىدى:\n"
"\n"
"%s"

#: ../apport/ui.py:1447 ../apport/ui.py:1454
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1447
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1454
msgid "Problem already known"
msgstr "مەسىلە ئاللىقاچان ئايدىڭلاشقان"

#: ../apport/ui.py:1448
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1448
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"توركۆرگۈدىكى كەمتۈك دوكلاتىدا بۇ مەسىلە ئاللىقاچان مەلۇم قىلىنغان. تەكشۈرۈپ "
"كۆرۈڭ، ئەگەر سىزنىڭ مەلۇماتىڭىزدا تېخىمۇ كۆپرەك ئۇچۇرلار بار بولسا "
"ئىجادىيەتچىلەر ئۈچۈن تېخىمۇ پايدىلىق بولاتتى."

#: ../apport/ui.py:1455
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1455
msgid "This problem was already reported to developers. Thank you!"
msgstr "مەسىلە ئىجادىيەتچىلەرگە مەلۇم قىلىندى. سىزگە تەشەككۈر!"

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
#: ../data/apportcheckresume.py:67
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr ""
"بۇ ئالدىنقى قېتىملىق توڭدا(suspend) دە يۈز بەرگەن بولۇپ، سىستېمىنى نورمال "
"داۋام قىلغىلى بولمىدى."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:69
#: ../data/apportcheckresume.py:69
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr ""
"بۇ ئالدىنقى قېتىملىق ئۈچەكتە(hibernation) دە يۈز بەرگەن بولۇپ، سىستېمىنى "
"نورمال داۋام قىلغىلى بولمىدى."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:74
#: ../data/apportcheckresume.py:74
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"ئەسلىگە قايتۇرۇش باسقۇچى ئاخىرلىشاي دەپ قالدى، بۇنداق بولغاندا نورمال "
"تاماملىنىدۇ."

#: ../bin/apport-cli.py:80 ../debian/tmp/usr/bin/apport-cli.py:80
msgid "Press any key to continue..."
msgstr "خالىغان كۇنۇپكىنى باسسىڭىز داۋاملىشىدۇ..."

#: ../bin/apport-cli.py:87 ../debian/tmp/usr/bin/apport-cli.py:87
msgid "What would you like to do? Your options are:"
msgstr "نېمە قىلغۇڭىز بار؟ سىز تۆۋەندىكىلەرنى قىلالايسىز:"

#: ../bin/apport-cli.py:100 ../debian/tmp/usr/bin/apport-cli.py:100
#, python-format
msgid "Please choose (%s):"
msgstr "تاللاڭ(%s):"

#: ../bin/apport-cli.py:164 ../debian/tmp/usr/bin/apport-cli.py:164
#, python-format
msgid "(%i bytes)"
msgstr "(%i بايت)"

#: ../bin/apport-cli.py:195 ../debian/tmp/usr/bin/apport-cli.py:195
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"مەلۇماتنى ئەۋەتىپ بولغاندىن كېيىن \n"
"توركۆرگۈدە ئېچىلغان بەتتىكى جەدۋەلنى تولدۇرۇڭ."

#: ../bin/apport-cli.py:198 ../debian/tmp/usr/bin/apport-cli.py:198
#, python-format
msgid "&Send report (%s)"
msgstr "مەلۇمات (%s) نى ئەۋەت(&S)"

#: ../bin/apport-cli.py:202 ../debian/tmp/usr/bin/apport-cli.py:202
msgid "&Examine locally"
msgstr "يەرلىكتە تەكشۈر(&E)"

#: ../bin/apport-cli.py:206 ../debian/tmp/usr/bin/apport-cli.py:206
msgid "&View report"
msgstr "مەلۇمات كۆرسەت(&V)"

#: ../bin/apport-cli.py:207 ../debian/tmp/usr/bin/apport-cli.py:207
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"كېيىن يەنە باشقىلارغا ئەۋەتىش ياكى كۆچۈرۈپ بېرىش ئۈچۈن مەلۇمات ھۆججىتى "
"ساقلاپ قوي(&K)"

#: ../bin/apport-cli.py:208 ../debian/tmp/usr/bin/apport-cli.py:208
msgid "Cancel and &ignore future crashes of this program version"
msgstr ""
"پروگراممىنىڭ مەزكۇر نەشرىدە بۇنىڭدىن كېلىپ چىققان crashes نى ئەمەلدىن قالدۇر "
"ياكى پىسەنت قىلما(&I)"

#: ../bin/apport-cli.py:210 ../bin/apport-cli.py:287 ../bin/apport-cli.py:319
#: ../bin/apport-cli.py:340 ../debian/tmp/usr/bin/apport-cli.py:210
#: ../debian/tmp/usr/bin/apport-cli.py:287
#: ../debian/tmp/usr/bin/apport-cli.py:319
#: ../debian/tmp/usr/bin/apport-cli.py:340
msgid "&Cancel"
msgstr "ئەمەلدىن قالدۇر(&C)"

#: ../bin/apport-cli.py:238 ../debian/tmp/usr/bin/apport-cli.py:238
msgid "Problem report file:"
msgstr "مەلۇمات ھۆججىتى:"

#: ../bin/apport-cli.py:244 ../bin/apport-cli.py:249
#: ../debian/tmp/usr/bin/apport-cli.py:244
#: ../debian/tmp/usr/bin/apport-cli.py:249
msgid "&Confirm"
msgstr "جەزملە(&C)"

#: ../bin/apport-cli.py:248 ../debian/tmp/usr/bin/apport-cli.py:248
#, python-format
msgid "Error: %s"
msgstr "خاتالىق: %s"

#: ../bin/apport-cli.py:255 ../debian/tmp/usr/bin/apport-cli.py:255
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"ئىجادىيەتچىلەرنىڭ پروگراممىنى مۇكەممەللەشتۈرۈشى ئۈچۈن \n"
"توپلانغان ئۇچۇرلارنى ئەۋەتىدۇ. بۇنىڭغا ئازراق ۋاقىت كېتىدۇ."

#: ../bin/apport-cli.py:268 ../debian/tmp/usr/bin/apport-cli.py:268
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"توپلانغان ئۇچۇرلارنى كەمتۈك باشقۇرۇش سىستېمىسىغا ئەۋەتىدۇ.\n"
"بۇنىڭغا ئازراق ۋاقىت كېتىدۇ."

#: ../bin/apport-cli.py:318 ../debian/tmp/usr/bin/apport-cli.py:318
msgid "&Done"
msgstr "تامام(&D)"

#: ../bin/apport-cli.py:324 ../debian/tmp/usr/bin/apport-cli.py:324
msgid "none"
msgstr "يوق"

#: ../bin/apport-cli.py:325 ../debian/tmp/usr/bin/apport-cli.py:325
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "تاللانغىنى : %s. كوپنى تاللاش:"

#: ../bin/apport-cli.py:341 ../debian/tmp/usr/bin/apport-cli.py:341
msgid "Choices:"
msgstr "تاللاشلار:"

#: ../bin/apport-cli.py:355 ../debian/tmp/usr/bin/apport-cli.py:355
msgid "Path to file (Enter to cancel):"
msgstr "ھۆججەتنىڭ يولى(بولدى قىلىش ئۈچۈن قايتۇرۇش كۇنۇپكىسىنى بېسىڭ):"

#: ../bin/apport-cli.py:361 ../debian/tmp/usr/bin/apport-cli.py:361
msgid "File does not exist."
msgstr "ھۆججەت مەۋجۇت ئەمەس."

#: ../bin/apport-cli.py:363 ../debian/tmp/usr/bin/apport-cli.py:363
msgid "This is a directory."
msgstr "بۇ بىر مۇندەرىجە."

#: ../bin/apport-cli.py:369 ../debian/tmp/usr/bin/apport-cli.py:369
msgid "To continue, you must visit the following URL:"
msgstr "داۋاملاشتۇرۇش ئۈچۈن تۆۋەندىكى URL نى كۆرۈشىڭىز كېرەك:"

#: ../bin/apport-cli.py:371 ../debian/tmp/usr/bin/apport-cli.py:371
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"ئەمدى توركۆرگۈنى قوزغىتىڭ ياكى، URL نى باشقا كومپيۇتېردىكى توركۆرگۈگە "
"كۆچۈرۈڭ."

#: ../bin/apport-cli.py:373 ../debian/tmp/usr/bin/apport-cli.py:373
msgid "Launch a browser now"
msgstr "ھازىرلا توركۆرگۈنى قوزغىتىش"

#: ../bin/apport-cli.py:388 ../debian/tmp/usr/bin/apport-cli.py:388
msgid "No pending crash reports. Try --help for more information."
msgstr ""
"تېخى بىر تەرەپ قىلىنمىغان crash ھەققىدىكى مەلۇمات يوق. --help نى ئىشلەتسىڭىز "
"تېخىمۇ كوپ ئۇچۇرغا ئېرىشەلەيسىز."

#~ msgid "%prog [options] <apport problem report | crash ID>"
#~ msgstr "%prog [options] <apport problem report | crash ID>"

#~ msgid "incorrect number of arguments; use --help for a short help"
#~ msgstr ""
#~ "argument لارنىڭ سانى توغرا ئەمەس. --help نى ئىشلىتىپ قىسقىچە چۈشەندۈرۈشىنى "
#~ "كۆرۈڭ."

#, python-format
#~ msgid "Sorry, the program \"%s\" closed unexpectedly."
#~ msgstr "كەچۈرۈڭ، پروگرامما «%s» ئويلىمىغان يەردىن تاقىلىپ قالدى."

#, python-format
#~ msgid "Sorry, the package \"%s\" failed to install or upgrade."
#~ msgstr "كەچۈرۈڭ، بوغچا «%s» نى ئورنىتىش ياكى يۈكسەلدۈرۈش مەغلۇپ بولدى."

#~ msgid "Your system encountered a serious kernel problem."
#~ msgstr "سىستېمىڭىزنىڭ يادروسىدا(kernel) ئېغىر مەسىلە يۈز بەردى."

#~ msgid "Kernel problem"
#~ msgstr "يادرو(kernel) دىكى مەسىلە"

#~ msgid "Send this data to the developers?"
#~ msgstr "بۇ سانلىق-مەلۇماتلارنى ئىجادىيەتچىگە ئەۋەتسۇنمۇ؟"

#~ msgid ""
#~ "This occured during a previous suspend and prevented it from resuming "
#~ "properly."
#~ msgstr ""
#~ "بۇ ئالدىنقى قېتىملىق توڭلىتىش جەريانىدا يۈز بەرگەن بولۇپ، قايتا باشلاشقا "
#~ "بولمىدى."

#~ msgid ""
#~ "This occured during a previous hibernate and prevented it from resuming "
#~ "properly."
#~ msgstr ""
#~ "بۇ ئالدىنقى قېتىملىق ئۈچەككە كىرگۈزۈش جەريانىدا يۈز بەرگەن بولۇپ، قايتا "
#~ "باشلاشقا بولمىدى."

#, no-c-format
#~ msgid ""
#~ "<span weight=\"bold\" size=\"larger\">Sorry, the package \"%s\" failed to "
#~ "install or upgrade.</span>"
#~ msgstr ""
#~ "<span weight=\"bold\" size=\"larger\">كەچۈرۈڭ، بوغچا «%s» نى ئورنىتىش ياكى "
#~ "يۈكسەلدۈرۈش مەغلۇپ بولدى.</span>"

#~ msgid "Package problem"
#~ msgstr "بوغچىدىكى مەسىلە"

#, python-format
#~ msgid "This is not a genuine %s package"
#~ msgstr "بۇ رەسمىي  %s بوغچىسى ئەمەس"

#, python-format
#~ msgid "The package \"%s\" failed to install or upgrade."
#~ msgstr "بوغچا «%s» نى ئورنىتىش ياكى يېڭىلاش مەغلۇپ بولدى."

#~ msgid ""
#~ "you either need to do a local operation (-s, -g, -o) or supply an "
#~ "authentication file (--auth); see --help for a short help"
#~ msgstr ""
#~ "يەرلىكتە مەشغۇلات قىلىشىڭىز (-s، -g، -o) ياكى سالاھىيەت دەلىللەش ھۆججىتىنى (-"
#~ "-auth) تەمىنلىشىڭىز كېرەك. ئاددىي ياردەم ئۇچۇرىغا ئېرىشىش ئۈچۈن --help نى "
#~ "ئىشلىتىڭ."

#, python-format
#~ msgid "Sorry, the application %s has closed unexpectedly."
#~ msgstr "كەچۈرۈڭ بۇ %s ئەپ تاسادىپىي تاقالدى."

#~ msgid "Your system might become unstablenow and might need to be restarted."
#~ msgstr ""
#~ "سىستېمىڭىزنىڭ بىنورمال بولۇش ئېھتىماللىقى بار، شۇڭا قايتا قوزغىتىش زۆرۈر."
